### ISSUE TITLE
Failing start the camel-k-operator 1.0.0.-M3-SNAPSHOT with the minishifit

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-k#1015]
I tried to build the 1.0.0-M3-SNAPSHOT and run with the minishifit

Environments
```
go version go1.12.7 linux/amd64
```
```
operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"
```
```
minishift v1.32.0+009893b
```
```
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.38:8443
kubernetes v1.11.0+d4cacc0
```

Build steps
```
cd ${GOPATH}
export GO111MODULE=on
eval $(minishift docker-env)
docker login -u developer -p $(oc whoami -t) $(minishift openshift registry)
make
make images
```

The image has been in the container registry
```
docker images |grep apache/camel-k
docker.io/apache/camel-k                                 1.0.0-M3-SNAPSHOT   ea053a2e70d0        35 minutes ago      487 MB
docker.io/apache/camel-k                                 0.3.3               7895a2e3beab        5 months ago        531 MB
```

Run the kamel to install the operator but it starts to failing with the following logs messages
```

  | {"level":"info","ts":1571281281.439953,"logger":"cmd","msg":"Go Version: go1.12.7"}
-- | --
  | {"level":"info","ts":1571281281.4399931,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
  | {"level":"info","ts":1571281281.4400017,"logger":"cmd","msg":"Operator SDK Version: v0.10.0"}
  | {"level":"info","ts":1571281281.4400082,"logger":"cmd","msg":"Kaniko Version: 0.9.0"}
  | {"level":"info","ts":1571281281.4400148,"logger":"cmd","msg":"Camel K Operator Version: 1.0.0-M3-SNAPSHOT"}
  | {"level":"info","ts":1571281281.4400218,"logger":"cmd","msg":"Camel K Git Commit: 1879bcef4e3891ab22f3e17c27c2c9fb456d8221"}
  | {"level":"info","ts":1571281281.4402616,"logger":"leader","msg":"Trying to become the leader."}
  | {"level":"info","ts":1571281281.4929845,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
  | {"level":"info","ts":1571281281.4930205,"logger":"leader","msg":"Continuing as the leader."}
  | {"level":"info","ts":1571281281.528657,"logger":"cmd","msg":"Registering Components."}
  | {"level":"info","ts":1571281281.563894,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.564061,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"build-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5654223,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5655665,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.565661,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5657647,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integration-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5678048,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5678418,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5678666,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integrationkit-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.569036,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"integrationplatform-controller","source":"kind source: /, Kind="}
  | {"level":"info","ts":1571281281.5690634,"logger":"cmd","msg":"Starting the Cmd."}
  | {"level":"info","ts":1571281281.6693687,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"integrationplatform-controller"}
  | {"level":"info","ts":1571281281.6694808,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"build-controller"}
  | {"level":"info","ts":1571281281.6695075,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"integration-controller"}
  | {"level":"info","ts":1571281281.6695294,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"integrationkit-controller"}
  | {"level":"info","ts":1571281281.7696512,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"integrationkit-controller","worker count":1}
  | {"level":"info","ts":1571281281.7698083,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"integrationplatform-controller","worker count":1}
  | {"level":"info","ts":1571281281.769954,"logger":"camel-k.controller.integrationplatform","msg":"Reconciling IntegrationPlatform","request-namespace":"myproject","request-name":"camel-k"}
  | {"level":"info","ts":1571281281.7700257,"logger":"camel-k.controller.integrationplatform","msg":"Invoking action monitor","request-namespace":"myproject","request-name":"camel-k","api-version":"camel.apache.org/v1alpha1","kind":"IntegrationPlatform","ns":"myproject","name":"camel-k"}
  | {"level":"info","ts":1571281281.772297,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"build-controller","worker count":1}
  | {"level":"info","ts":1571281281.7725916,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"myproject","request-name":"jvm"}
  | {"level":"info","ts":1571281281.7727869,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"myproject","request-name":"groovy"}
  | {"level":"info","ts":1571281281.772869,"logger":"camel-k.controller.build","msg":"Invoking action monitor-routine","request-namespace":"myproject","request-name":"groovy","api-version":"camel.apache.org/v1alpha1","kind":"Build","ns":"myproject","name":"groovy"}
  | {"level":"info","ts":1571281281.7805097,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"integration-controller","worker count":1}
  | {"level":"info","ts":1571281281.8004694,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"myproject","request-name":"kotlin"}
  | {"level":"info","ts":1571281281.8005166,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"myproject","request-name":"groovy"}
  | {"level":"info","ts":1571281281.800536,"logger":"camel-k.controller.build","msg":"Invoking action schedule-routine","request-namespace":"myproject","request-name":"groovy","api-version":"camel.apache.org/v1alpha1","kind":"Build","ns":"myproject","name":"groovy"}
  | {"level":"info","ts":1571281281.8071918,"logger":"camel-k.controller.build","msg":"Build state transition","request-namespace":"myproject","request-name":"groovy","api-version":"camel.apache.org/v1alpha1","kind":"Build","ns":"myproject","name":"groovy","phase":"Running"}
  | {"level":"info","ts":1571281281.8113296,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"myproject","request-name":"groovy"}
  | {"level":"info","ts":1571281281.81138,"logger":"camel-k.controller.build","msg":"Invoking action monitor-routine","request-namespace":"myproject","request-name":"groovy","api-version":"camel.apache.org/v1alpha1","kind":"Build","ns":"myproject","name":"groovy"}
  | {"level":"info","ts":1571281281.9142787,"logger":"camel-k.builder","msg":"steps: [github.com/apache/camel-k/pkg/builder/GenerateProject@10 github.com/apache/camel-k/pkg/builder/InjectDependencies@12 github.com/apache/camel-k/pkg/builder/SanitizeDependencies@13 github.com/apache/camel-k/pkg/builder/ComputeDependencies@20 github.com/apache/camel-k/pkg/builder/IncrementalPackager@30 github.com/apache/camel-k/pkg/builder/s2i/Publisher@40]"}
  | {"level":"info","ts":1571281281.9143124,"logger":"camel-k.builder","msg":"executing step","step":"github.com/apache/camel-k/pkg/builder/GenerateProject","phase":10,"kit":"groovy"}
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x156e816]
  | goroutine 423 [running]:
  | github.com/apache/camel-k/pkg/builder.NewMavenProject(0xc000982f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  | /home/zhfeng/go/src/github.com/apache/camel-k/pkg/builder/builder_utils.go:73 +0x236
  | github.com/apache/camel-k/pkg/builder.generateProject(0xc000982f00, 0x367f7b4b, 0x309abdbb6c2)
  | /home/zhfeng/go/src/github.com/apache/camel-k/pkg/builder/builder_steps.go:117 +0x43
  | github.com/apache/camel-k/pkg/builder.(*stepWrapper).Execute(0xc000516ae0, 0xc000982f00, 0x2ca7c80, 0xe)
  | /home/zhfeng/go/src/github.com/apache/camel-k/pkg/builder/builder_types.go:77 +0x34
  | github.com/apache/camel-k/pkg/builder.(*defaultBuilder).Build(0xc0004a18f0, 0xc0005428f4, 0x6, 0x0, 0x0, 0xc000542910, 0x9, 0xc00003e960, 0x4f, 0xc0006e8510, ...)
  | /home/zhfeng/go/src/github.com/apache/camel-k/pkg/builder/builder.go:164 +0x174c
  | github.com/apache/camel-k/pkg/controller/build.(*scheduleRoutineAction).build(0xc000821090, 0x1d4eea0, 0xc0000b0018, 0xc000104d80)
  | /home/zhfeng/go/src/github.com/apache/camel-k/pkg/controller/build/schedule_routine.go:107 +0x11c
  | created by github.com/apache/camel-k/pkg/controller/build.(*scheduleRoutineAction).Handle
  | /home/zhfeng/go/src/github.com/apache/camel-k/pkg/controller/build/schedule_routine.go:99 +0x48


```

So is there anything I missed ?

**Comment by zhfeng** [comment]
Well, it could be resolved by cleaning the camel-k installation.
```
oc delete all,pvc,configmap,rolebindings,clusterrolebindings,secrets,sa,roles,clusterroles,crd -l 'app=camel-k'
```
and rebuild the images dev with
```
make images-dev
```
