### ISSUE TITLE
broken routes.js example

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-k#1065]
the routes.js example is broken while trying to use a processor.

**Comment by hguerrero** [comment]
Stacktrace: 

```[1] 2019-11-20 16:33:18.921 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@5be6e01c
[1] 2019-11-20 16:33:18.925 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@be64738
[1] 2019-11-20 16:33:18.927 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@48e4374
[1] 2019-11-20 16:33:19.023 INFO  [main] RuntimeSupport - Looking up loader for language: js
[1] 2019-11-20 16:33:19.329 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.js.JavaScriptRoutesLoader@dd0c991 for language js from service definition
[1] 2019-11-20 16:33:20.020 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/routes.js?language=js
[1] 2019-11-20 16:33:20.021 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@be64738 executed in phase ConfigureRoutes
[1] 2019-11-20 16:33:20.115 INFO  [main] MainSupport - Using properties from classpath:application.properties
[1] Exception in thread "main" TypeError: invokeMember on JavaObject[Route(js)[From[timer:js?period=1s] -> [SetBody[org.apache.camel.builder.ExpressionClause@6ae7deac]]] (org.apache.camel.model.RouteDefinition)] failed due to: Multiple applicable overloads found for method name process (candidates: [Method[public org.apache.camel.model.ProcessorDefinition org.apache.camel.model.ProcessorDefinition.process(java.util.function.Supplier)], Method[public org.apache.camel.model.ProcessorDefinition org.apache.camel.model.ProcessorDefinition.process(org.apache.camel.Processor)]], arguments: [DynamicObject<JSFunction>@73017a80 (DynamicObjectBasic)])
[1] 	at <js> :program(Unnamed:28-34:1057-1258)
[1] 	at org.graalvm.polyglot.Context.eval(Context.java:368)
[1] 	at org.apache.camel.k.loader.js.JavaScriptRoutesLoader$1.configure(JavaScriptRoutesLoader.java:59)
[1] 	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:457)
[1] 	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:424)
[1] 	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:404)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$addRoutes$0(AbstractCamelContext.java:1113)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2456)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1113)
[1] 	at org.apache.camel.main.MainSupport.postProcessCamelContext(MainSupport.java:785)
[1] 	at org.apache.camel.main.MainSupport.initCamelContext(MainSupport.java:652)
[1] 	at org.apache.camel.main.Main.doInit(Main.java:108)
[1] 	at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:62)
[1] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:90)
[1] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:197)
[1] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[1] 	at org.apache.camel.k.main.Application.main(Application.java:44)
[1] 2019-11-20 16:33:25.425 INFO  [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.
integration "routes" updated```
