### ISSUE TITLE
No component found with scheme: http4 // Camel-k 1.0.0M4

### ISSUE THREAD

**Issue by contactreji** [apache/camel-k#1072]
Hey guys

I was testing following artifacts in my new installation of camel-k 1.0.0 M5 kit.

```
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns="http://camel.apache.org/schema/spring" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
   <route streamCache="true">
      <from uri="jetty:http://0.0.0.0:9090/address/lookup" />
      <log message="Received request to process : ${body}" />
      <setHeader name="CamelHttpUri">
         <simple>http://10.213.96.182:8080/pincode/${headers.countryName}/${headers.cityName}</simple>
      </setHeader>
      <setHeader name="CamelHttpMethod">
         <constant>GET</constant>
      </setHeader>
      <to uri="http4://10.213.96.182:8080" />
      <log message="Received response from external lookup : ${body}" />
      <setHeader name="pincode">
         <jsonpath>$.pincode</jsonpath>
      </setHeader>
      <to uri="sql:insert into address(countryname, cityname, postalcode) values(:#countryName,:#cityName,:#pincode)?dataSource=db5dc9a00fa7715b59aa24454c" />
      <log message="Processing completed. Returning payload ${body}" />
   </route>
</routes>


import org.apache.commons.dbcp.*;

beans { 
db5dc9a00fa7715b59aa24454c = [ driverClassName: 'com.mysql.jdbc.Driver', url: 'jdbc:mysql://10.213.96.182:3306/roma', username: 'user1', password: '*********',  ]  as  BasicDataSource
}

```

I used the following command to deploy above 2 files

```
 kamel run --dev --name=testapp --dependency mvn:mysql/mysql-connector-java:5.1.34 --dependency mvn:commons-dbcp/commons-dbcp:1.4 --logging-level org.apache.camel.k=DEBUG  route.xml registry.groovy
```

And I get following failures in log 

```
integration "testapp" created
integration "testapp" in phase Initialization
integration "testapp" in phase Building Kit
integration "testapp" in phase Deploying
integration "testapp" in phase Running
[1] Monitoring pod testapp-58dd4697c7-k5x45[1] Starting the Java application using /opt/run-java/run-java.sh ...
[1] exec java -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp ./resources:/etc/camel/conf:/etc/camel/resources:/etc/camel/sources/i-source-000:/etc/camel/sources/i-source-001:dependencies/com.github.ben-manes.caffeine.caffeine-2.8.0.jar:dependencies/com.jayway.jsonpath.json-path-2.4.0.jar:dependencies/com.sun.activation.javax.activation-1.2.0.jar:dependencies/com.sun.xml.bind.jaxb-core-2.3.0.1.jar:dependencies/com.sun.xml.bind.jaxb-impl-2.3.0.jar:dependencies/commons-dbcp.commons-dbcp-1.4.jar:dependencies/commons-io.commons-io-2.6.jar:dependencies/commons-pool.commons-pool-1.5.4.jar:dependencies/javax.servlet.javax.servlet-api-3.1.0.jar:dependencies/javax.xml.bind.jaxb-api-2.3.0.jar:dependencies/mysql.mysql-connector-java-5.1.34.jar:dependencies/net.minidev.accessors-smart-1.2.jar:dependencies/net.minidev.json-smart-2.3.jar:dependencies/net.minidev.json-smart-action-2.3.jar:dependencies/org.apache.camel.camel-api-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-attachments-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-base-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-bean-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-caffeine-lrucache-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-cloud-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-core-engine-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-endpointdsl-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-file-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-groovy-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-http-common-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-jaxp-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-jetty-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-jetty-common-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-jsonpath-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-main-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-management-api-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-sql-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-support-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-util-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-util-json-3.0.0-RC3.jar:dependencies/org.apache.camel.k.camel-k-loader-groovy-1.0.7.jar:dependencies/org.apache.camel.k.camel-k-loader-xml-1.0.7.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.0.7.jar:dependencies/org.apache.camel.k.camel-k-runtime-main-1.0.7.jar:dependencies/org.apache.camel.spi-annotations-3.0.0-RC3.jar:dependencies/org.apache.commons.commons-lang3-3.9.jar:dependencies/org.apache.logging.log4j.log4j-api-2.12.1.jar:dependencies/org.apache.logging.log4j.log4j-core-2.12.1.jar:dependencies/org.apache.logging.log4j.log4j-slf4j-impl-2.12.1.jar:dependencies/org.codehaus.groovy.groovy-2.5.8.jar:dependencies/org.eclipse.jetty.jetty-client-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-continuation-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-http-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-io-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-jmx-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-security-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-server-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-servlet-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-servlets-9.4.20.v20190813.jar:dependencies/org.eclipse.jetty.jetty-util-9.4.20.v20190813.jar:dependencies/org.ow2.asm.asm-5.0.4.jar:dependencies/org.slf4j.slf4j-api-1.7.28.jar:dependencies/org.springframework.spring-beans-5.1.10.RELEASE.jar:dependencies/org.springframework.spring-core-5.1.10.RELEASE.jar:dependencies/org.springframework.spring-jcl-5.1.10.RELEASE.jar:dependencies/org.springframework.spring-jdbc-5.1.10.RELEASE.jar:dependencies/org.springframework.spring-tx-5.1.10.RELEASE.jar org.apache.camel.k.main.Application
[1] OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[1] 2019-11-21 23:58:45.444 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@460d0a57
[1] 2019-11-21 23:58:45.454 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@769f71a9
[1] 2019-11-21 23:58:45.455 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@6f96c77
[1] 2019-11-21 23:58:45.482 INFO  [main] RuntimeSupport - Looking up loader for language: xml
[1] 2019-11-21 23:58:45.493 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.xml.XmlRoutesLoader@481a996b for language xml from service definition
[1] 2019-11-21 23:58:45.497 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/route.xml?language=xml
[1] 2019-11-21 23:58:45.497 INFO  [main] RuntimeSupport - Looking up loader for language: groovy
[1] 2019-11-21 23:58:45.958 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.groovy.GroovyRoutesLoader@5038d0b5 for language groovy from service definition
[1] 2019-11-21 23:58:46.436 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-001/registry.groovy?language=groovy
[1] 2019-11-21 23:58:46.437 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@769f71a9 executed in phase ConfigureRoutes
[1] 2019-11-21 23:58:46.459 INFO  [main] BaseMainSupport - Using properties from: file:/etc/camel/conf/application.properties
[1] 2019-11-21 23:58:47.408 DEBUG [main] XmlRoutesLoader - Loaded 1 routes from org.apache.camel.k.Sources$URI@352e787a
[1] 2019-11-21 23:58:48.502 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.ContextConfigurer@460d0a57 executed in phase ConfigureContext
[1] 2019-11-21 23:58:48.503 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) is starting
[1] 2019-11-21 23:58:48.505 INFO  [main] DefaultManagementStrategy - JMX is disabled
[1] 2019-11-21 23:58:48.972 WARN  [main] JettyHttpComponent9 - JMX disabled in CamelContext. Jetty JMX extensions will remain disabled.
[1] 2019-11-21 23:58:49.247 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) is shutting down
[1] 2019-11-21 23:58:49.250 INFO  [main] MainLifecycleStrategy - CamelContext: camel-k has been shutdown, triggering shutdown of the JVM.
[1] 2019-11-21 23:58:49.260 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) uptime 0.755 seconds
[1] 2019-11-21 23:58:49.260 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) is shutdown in 0.013 seconds
[1] 2019-11-21 23:58:49.261 ERROR [main] DefaultCamelContext - Error starting CamelContext (camel-k) due to exception thrown: Failed to create route route1 at: >>> To[http4://10.213.96.182:8080] <<< in route: Route(route1)[From[jetty:http://0.0.0.0:9090/address/lookup]... because of Failed to resolve endpoint: http4://10.213.96.182:8080 due to: No component found with scheme: http4
[1] org.apache.camel.FailedToCreateRouteException: Failed to create route route1 at: >>> To[http4://10.213.96.182:8080] <<< in route: Route(route1)[From[jetty:http://0.0.0.0:9090/address/lookup]... because of Failed to resolve endpoint: http4://10.213.96.182:8080 due to: No component found with scheme: http4
[1]     at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:379) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:108) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.DefaultModel.start(DefaultModel.java:326) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.DefaultModel.startRoute(DefaultModel.java:300) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.DefaultModel.startRouteDefinitions(DefaultModel.java:293) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.DefaultModel.startRouteDefinitions(DefaultModel.java:272) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.AbstractModelCamelContext.startRouteDefinitions(AbstractModelCamelContext.java:322) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2590) ~[org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.java:2438) ~[org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2455) ~[org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2436) ~[org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:99) ~[org.apache.camel.camel-api-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2345) [org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doStart(ApplicationRuntime.java:177) [org.apache.camel.k.camel-k-runtime-main-1.0.7.jar:1.0.7]
[1]     at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:99) [org.apache.camel.camel-api-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.main.MainSupport.run(MainSupport.java:77) [org.apache.camel.camel-main-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70) [org.apache.camel.k.camel-k-runtime-main-1.0.7.jar:1.0.7]
[1]     at org.apache.camel.k.main.Application.main(Application.java:42) [org.apache.camel.k.camel-k-runtime-main-1.0.7.jar:1.0.7]
[1] Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: http4://10.213.96.182:8080 due to: No component found with scheme: http4
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:807) ~[org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.impl.engine.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:127) ~[org.apache.camel.camel-base-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:41) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:34) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.ProcessorReifier.makeProcessorImpl(ProcessorReifier.java:574) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:540) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:250) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:377) ~[org.apache.camel.camel-core-engine-3.0.0-RC3.jar:3.0.0-RC3]
[1]     ... 17 more
[1] Exception in thread "main" org.apache.camel.FailedToCreateRouteException: Failed to create route route1 at: >>> To[http4://10.213.96.182:8080] <<< in route: Route(route1)[From[jetty:http://0.0.0.0:9090/address/lookup]... because of Failed to resolve endpoint: http4://10.213.96.182:8080 due to: No component found with scheme: http4
[1]     at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:379)
[1]     at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:108)
[1]     at org.apache.camel.impl.DefaultModel.start(DefaultModel.java:326)
[1]     at org.apache.camel.impl.DefaultModel.startRoute(DefaultModel.java:300)
[1]     at org.apache.camel.impl.DefaultModel.startRouteDefinitions(DefaultModel.java:293)
[1]     at org.apache.camel.impl.DefaultModel.startRouteDefinitions(DefaultModel.java:272)
[1]     at org.apache.camel.impl.AbstractModelCamelContext.startRouteDefinitions(AbstractModelCamelContext.java:322)
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2590)
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.java:2438)
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2455)
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2436)
[1]     at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:99)
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2345)
[1]     at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doStart(ApplicationRuntime.java:177)
[1]     at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:99)
[1]     at org.apache.camel.main.MainSupport.run(MainSupport.java:77)
[1]     at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[1]     at org.apache.camel.k.main.Application.main(Application.java:42)
[1] Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: http4://10.213.96.182:8080 due to: No component found with scheme: http4
[1]     at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:807)
[1]     at org.apache.camel.impl.engine.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:127)
[1]     at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:41)
[1]     at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:34)
[1]     at org.apache.camel.reifier.ProcessorReifier.makeProcessorImpl(ProcessorReifier.java:574)
[1]     at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:540)
[1]     at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:250)
[1]     at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:377)
[1]     ... 17 more
[1] 2019-11-21 23:58:49.278 INFO  [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.

```

Should I pass the dependencies **explicitly** in this particular case?

**Comment by contactreji** [comment]
I am currently in process of migrating from 0.3.4  to version 1.0.0 M4. Thats when I hit this issue.

**Comment by jamesnetherton** [comment]
The `http4` URI scheme no longer exists in Camel 3. See the [migration guide](https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_renamed_components). 

You can use the plain old `http` component / scheme.

**Comment by contactreji** [comment]
Thanks @jamesnetherton . This helped. Closing the issue
