### ISSUE TITLE
Ignore package when working with Java classes

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-k#1132]
if trying to run a Java based integration that has `package com.example;` or any other package names causes a `java.lang.NullPointerException`, removing the package line returns a successful execution.

If packages are note required, then when receiving an integration that includes package word, remove it from the code and proceed to avoid the null pointer exception. 

Full log:

```2019-12-10 21:19:38.753 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.java.JavaSourceRoutesLoader@67a20f67 for language java from service definition
[4] Exception in thread "main" org.apache.camel.RuntimeCamelException: java.lang.NullPointerException
[4]     at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:52)
[4]     at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:69)
[4]     at org.apache.camel.k.listener.RoutesConfigurer.accept(RoutesConfigurer.java:51)
[4]     at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:32)
[4]     at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.lambda$invokeListeners$0(ApplicationRuntime.java:152)
[4]     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[4]     at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
[4]     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[4]     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[4]     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[4]     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[4]     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[4]     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[4]     at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.invokeListeners(ApplicationRuntime.java:151)
[4]     at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.beforeStart(ApplicationRuntime.java:125)
[4]     at org.apache.camel.main.MainSupport.beforeStart(MainSupport.java:114)
[4]     at org.apache.camel.main.MainSupport.run(MainSupport.java:76)
[4]     at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[4]     at org.apache.camel.k.main.Application.main(Application.java:42)
[4] Caused by: java.lang.NullPointerException
[4]     at org.joor.Reflect.create(Reflect.java:697)
[4]     at org.joor.Reflect.create(Reflect.java:662)
[4]     at org.apache.camel.k.loader.java.JavaSourceRoutesLoader.load(JavaSourceRoutesLoader.java:47)
[4]     at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:67)
[4]     ... 17 more```

**Comment by lburgazzoli** [comment]
this issue should have been fixed long time ago, can you share the java code ?

**Comment by hguerrero** [comment]
I'm trying this: https://raw.githubusercontent.com/hguerrero/camel-netty-proxy/master/src/main/java/com/github/zregvart/cnp/ProxyRoute.java
