### ISSUE TITLE
Basic javascript example generates "Multiple applicable overloads found for method name process"

### ISSUE THREAD

**Issue by jcordes73** [apache/camel-k#1144]
Starting the Java application using /opt/run-java/run-java.sh ...
exec java -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp ./resources:/etc/camel/conf:/etc/camel/resources:/etc/camel/sources/i-source-000:dependencies/com.ibm.icu.icu4j-62.1.jar:dependencies/com.sun.xml.bind.jaxb-core-2.3.0.1.jar:dependencies/com.sun.xml.bind.jaxb-impl-2.3.0.jar:dependencies/commons-io.commons-io-2.6.jar:dependencies/javax.xml.bind.jaxb-api-2.3.0.jar:dependencies/org.apache.camel.camel-api-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-base-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-core-engine-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-endpointdsl-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-jaxp-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-log-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-main-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-management-api-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-support-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-timer-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-util-3.0.0-RC3.jar:dependencies/org.apache.camel.camel-util-json-3.0.0-RC3.jar:dependencies/org.apache.camel.k.camel-k-loader-js-1.0.7.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.0.7.jar:dependencies/org.apache.camel.k.camel-k-runtime-main-1.0.7.jar:dependencies/org.apache.camel.spi-annotations-3.0.0-RC3.jar:dependencies/org.apache.commons.commons-lang3-3.9.jar:dependencies/org.apache.logging.log4j.log4j-api-2.12.1.jar:dependencies/org.apache.logging.log4j.log4j-core-2.12.1.jar:dependencies/org.apache.logging.log4j.log4j-slf4j-impl-2.12.1.jar:dependencies/org.graalvm.js.js-19.2.0.1.jar:dependencies/org.graalvm.regex.regex-19.2.0.1.jar:dependencies/org.graalvm.sdk.graal-sdk-19.2.0.1.jar:dependencies/org.graalvm.truffle.truffle-api-19.2.0.1.jar:dependencies/org.ow2.asm.asm-6.2.1.jar:dependencies/org.ow2.asm.asm-analysis-6.2.1.jar:dependencies/org.ow2.asm.asm-commons-6.2.1.jar:dependencies/org.ow2.asm.asm-tree-6.2.1.jar:dependencies/org.ow2.asm.asm-util-6.2.1.jar:dependencies/org.slf4j.slf4j-api-1.7.28.jar org.apache.camel.k.main.Application
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2019-12-13 21:59:29.803 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@5276e6b0
2019-12-13 21:59:29.807 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@778d1062
2019-12-13 21:59:29.808 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@49c386c8
2019-12-13 21:59:29.825 INFO  [main] RuntimeSupport - Looking up loader for language: js
2019-12-13 21:59:29.931 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.js.JavaScriptRoutesLoader@683dbc2c for language js from service definition
2019-12-13 21:59:30.214 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/hello.js?language=js
2019-12-13 21:59:30.214 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@778d1062 executed in phase ConfigureRoutes
2019-12-13 21:59:30.235 INFO  [main] BaseMainSupport - Using properties from: file:/etc/camel/conf/application.properties
When trying to use a basic Javascript (https://camel.apache.org/camel-k/latest/languages/javascript.html) example with Camel K Client 1.0.0-M4 the following error can be seen in the log of the pod:

Exception in thread "main" TypeError: invokeMember (process) on JavaObject[Route[From[timer:tick] -> []] (org.apache.camel.model.RouteDefinition)] failed due to: Multiple applicable overloads found for method name process (candidates: [Method[public org.apache.camel.model.ProcessorDefinition org.apache.camel.model.ProcessorDefinition.process(org.apache.camel.Processor)], Method[public org.apache.camel.model.ProcessorDefinition org.apache.camel.model.ProcessorDefinition.process(java.util.function.Supplier)]], arguments: [DynamicObject<JSFunction>@6a2eea2a (DynamicObjectBasic)])
        at <js> :program(Unnamed:5-6:77-113)
        at org.graalvm.polyglot.Context.eval(Context.java:370)
        at org.apache.camel.k.loader.js.JavaScriptRoutesLoader$1.configure(JavaScriptRoutesLoader.java:59)
        at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:471)
        at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:438)
        at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:418)
        at org.apache.camel.impl.engine.AbstractCamelContext.lambda$addRoutes$0(AbstractCamelContext.java:1114)
        at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2455)
        at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1114)
        at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:84)
        at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:549)
        at org.apache.camel.main.BaseMainSupport.initCamelContext(BaseMainSupport.java:402)
        at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doInit(ApplicationRuntime.java:168)
        at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:62)
        at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:90)
        at org.apache.camel.main.MainSupport.run(MainSupport.java:77)
        at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
        at org.apache.camel.k.main.Application.main(Application.java:42)
2019-12-13 21:59:31.384 INFO  [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.

**Comment by lburgazzoli** [comment]
Till we get it fixed, you can workaround it with
- https://github.com/apache/camel-k/blob/master/examples/routes.js#L22-L37
- https://github.com/apache/camel-k-runtime/blob/master/camel-k-loader-js/src/test/resources/routes-with-processors.js

**Comment by lburgazzoli** [comment]
should be fixed now
