### ISSUE TITLE
Unable to run Knative integration

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#1169]
Platform : `kamel` `Camel K Client 1.0.0-M4` on minikube 1.6.x using Knative serving/eventing `v0.11.0` and `CamelSource` `v0.10.3`

When I try to deploy this `JS` integration 

```javascript
from('knative:channel/camel-test-channel')
    .convertBodyTo(String.class)
    .to('log:info');
```
I get the following error when integrtion is started.

```
Dev Mode -- [1] Exception in thread "main" org.graalvm.polyglot.PolyglotException
Dev Mode -- [2] Exception in thread "main" org.graalvm.polyglot.PolyglotException
Dev Mode -- [2] 	at org.apache.camel.model.ConvertBodyDefinition.<init>(ConvertBodyDefinition.java:50)
[2] 	at org.apache.camel.model.ProcessorDefinition.convertBodyTo(ProcessorDefinition.java:2905)
[2] 	at <js> :program(Unnamed:1-2:15-89)
Dev Mode -- [2] 	at org.graalvm.polyglot.Context.eval(Context.java:370)
[2] 	at org.apache.camel.k.loader.js.JavaScriptRoutesLoader$1.configure(JavaScriptRoutesLoader.java:59)
[2] 	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:471)
[2] 	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:438)
[2] 	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:418)
Dev Mode -- [2] 	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$addRoutes$0(AbstractCamelContext.java:1114)
Dev Mode -- [1] 	at org.apache.camel.model.ConvertBodyDefinition.<init>(ConvertBodyDefinition.java:50)
[1] 	at org.apache.camel.model.ProcessorDefinition.convertBodyTo(ProcessorDefinition.java:2905)
Dev Mode -- [1] 	at <js> :program(Unnamed:1-2:15-89)
[1] 	at org.graalvm.polyglot.Context.eval(Context.java:370)
Dev Mode -- [1] 	at org.apache.camel.k.loader.js.JavaScriptRoutesLoader$1.configure(JavaScriptRoutesLoader.java:59)
[1] 	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:471)
Dev Mode -- [2] 	at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2455)
Dev Mode -- [1] 	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:438)
Dev Mode -- [1] 	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:418)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$addRoutes$0(AbstractCamelContext.java:1114)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2455)
Dev Mode -- [2] 	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1114)
[2] 	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:84)
[2] 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:549)
[2] 	at org.apache.camel.main.BaseMainSupport.initCamelContext(BaseMainSupport.java:402)
Dev Mode -- [2] 	at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doInit(ApplicationRuntime.java:168)
Dev Mode -- [2] 	at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:62)
[2] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:90)
[2] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:77)
Dev Mode -- [1] 	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1114)
[1] 	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:84)
Dev Mode -- [1] 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:549)
Dev Mode -- [1] 	at org.apache.camel.main.BaseMainSupport.initCamelContext(BaseMainSupport.java:402)
[1] 	at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doInit(ApplicationRuntime.java:168)
[1] 	at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:62)
Dev Mode -- [1] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:90)
[1] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:77)
[1] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[1] 	at org.apache.camel.k.main.Application.main(Application.java:42)
Dev Mode -- [1] Caused by host exception: java.lang.NullPointerException
Dev Mode -- [2] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
Dev Mode -- [2] 	at org.apache.camel.k.main.Application.main(Application.java:42)
Dev Mode -- [2] Caused by host exception: java.lang.NullPointerException
Dev Mode -- [2] 2019-12-20 13:35:30.295 [32mINFO [m [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.
Dev Mode -- [1] 2019-12-20 13:35:30.295 [32mINFO [m [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.
```

**Comment by lburgazzoli** [comment]
As you are using JavaScript, you can't use String.class as it is but you need to follow the graaljs interoperability guides, see https://github.com/graalvm/graaljs/blob/master/docs/user/JavaInterop.md#class-access

**Comment by lburgazzoli** [comment]
@kameshsampath is this still an issue ?

**Comment by kameshsampath** [comment]
No Luca, we can close this

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
