### ISSUE TITLE
Regression for groovy routes

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#118]
When I try to run the example I get:

```
[1] Monitoring pod routes-cfb6655dc-zvf7r[1] Starting the Java application using /opt/run-java/run-java.sh ...
[1] exec java -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/opt/prometheus/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp .:/deployments/dependencies/org.apache.camel.k/camel-k-runtime-jvm-0.0.3-SNAPSHOT.jar:/deployments/dependencies/org.slf4j/slf4j-api-1.7.25.jar:/deployments/dependencies/org.apache.logging.log4j/log4j-slf4j-impl-2.11.0.jar:/deployments/dependencies/org.apache.logging.log4j/log4j-api-2.11.0.jar:/deployments/dependencies/org.apache.logging.log4j/log4j-core-2.11.0.jar:/deployments/dependencies/org.jooq/joor-java-8-0.9.9.jar:/deployments/dependencies/commons-io/commons-io-2.6.jar:/deployments/dependencies/org.apache.commons/commons-lang3-3.8.jar:/deployments/dependencies/org.apache.camel/camel-core-2.22.1.jar:/deployments/dependencies/com.sun.xml.bind/jaxb-core-2.3.0.1.jar:/deployments/dependencies/com.sun.xml.bind/jaxb-impl-2.3.0.1.jar org.apache.camel.k.jvm.Application
[1] [INFO ] 2018-09-24 16:58:57.113 [main] Application - Routes: file:/etc/camel/conf/routes.groovy
[1] [INFO ] 2018-09-24 16:58:57.115 [main] Application - Language: groovy
[1] [INFO ] 2018-09-24 16:58:57.115 [main] Application - Locations: file:/etc/camel/conf/application.properties
[1] Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilerConfiguration
[1]     at org.apache.camel.k.jvm.RoutesLoaders$4$1.configure(RoutesLoaders.java:138)
[1]     at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:462)
[1]     at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:402)
[1]     at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:383)
[1]     at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1029)
[1]     at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1026)
[1]     at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3272)
[1]     at org.apache.camel.impl.DefaultCamelContext.addRoutes(DefaultCamelContext.java:1026)
[1]     at org.apache.camel.main.MainSupport.postProcessCamelContext(MainSupport.java:612)
[1]     at org.apache.camel.main.MainSupport.postProcessContext(MainSupport.java:550)
[1]     at org.apache.camel.main.Main.doStart(Main.java:136)
[1]     at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
[1]     at org.apache.camel.main.MainSupport.run(MainSupport.java:170)
[1]     at org.apache.camel.k.jvm.Application.main(Application.java:68)
[1] Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.control.CompilerConfiguration
[1]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[1]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[1]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[1]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[1]     ... 14 more
```

@oscerd , @zregvart do you think we have any chance to run a dev instance of Openshift in Apache CI?

Currently PR builds are disabled because there was a issue with dependencies, but I think it's easy to overcome that problem by checking-in the vendor dir... What about `minishift` / `oc cluster up` to avoid breaking things?

**Comment by lburgazzoli** [comment]
Looks like the algorithm to automatically detect the dependencies does no work for this case so you need to explicit require the camel-groovy dependency within kamel run or we need to add the groovy dependency if the files ends with .groovy or the language is set to groovy.

Will send a pr

**Comment by zregvart** [comment]
> @oscerd , @zregvart do you think we have any chance to run a dev instance of Openshift in Apache CI?

Not sure, I've created a build to see if the Docker is installed, from what I know is that some changes need to be made to the [Docker and firewall configuration](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux) to get the `oc cluster up` to work, so it might be a stretch.

**Comment by zregvart** [comment]
We could ask for a VM from INFRA.

**Comment by zregvart** [comment]
CI nodes have Docker version 17.05.0-ce, build 89658be installed, we can experiment with that to some extent but if I'm not mistaking for `oc cluster up` the Docker/firewall configuration needs to be modified.
