### ISSUE TITLE
Quarkus runner jar is never rebuilt on layered kits

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1387]
When building a new kit, the runner jar is not replaced and this causes issue.
E.g. When switching from an integration written in groovy (-t quarkus.enabled=true) to one written in Java, the groovy configuration is kept in the runner and we have a runtime problem.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
  at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:27)
Caused by: java.lang.RuntimeException: Failed to start quarkus
  at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:358)
  ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.language.groovy.GroovyLanguage
  at java.net.URLClassLoader.findClass(Unknown Source)
  at java.lang.ClassLoader.loadClass(Unknown Source)
  at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
  at java.lang.ClassLoader.loadClass(Unknown Source)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Unknown Source)
  at io.quarkus.deployment.steps.Core$factoryFinderResolver18.deploy_0(Core$factoryFinderResolver18.zig:158)
  at io.quarkus.deployment.steps.Core$factoryFinderResolver18.deploy(Core$factoryFinderResolver18.zig:36)
  at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:304)
  ... 1 more
```

**Comment by nicolaferraro** [comment]
Reproducer:

```
kamel reset
kamel init one.groovy
kamel run one.groovy -t quarkus.enabled=true -w
kamel delete one
kamel init Two.java
kamel run Two.java -t quarkus.enabled=true --logs

```
