### ISSUE TITLE
Cannot expose knative endpoints in YAML

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1539]
Works with other languages.

We need to add an e2e test as well.

*example.yaml*
```
- from:
    uri: "knative:endpoint/example"
    steps:
      - set-body:
          constant: "Hello Camel K from yaml"
      - to: "log:info"
```

Results in error:
```
[2] Exception in thread "main" org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: platform-http-router of type: org.apache.camel.component.platform.http.vertx.VertxPlatformHttpRouter
[2] 	at org.apache.camel.support.CamelContextHelper.mandatoryLookup(CamelContextHelper.java:240)
[2] 	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpRouter.lookup(VertxPlatformHttpRouter.java:265)
[2] 	at org.apache.camel.component.knative.http.KnativeHttpTransport.doStart(KnativeHttpTransport.java:78)
[2] 	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
[2] 	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:84)
[2] 	at org.apache.camel.component.knative.KnativeComponent.doStart(KnativeComponent.java:191)
[2] 	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
[2] 	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3075)
[2] 	at org.apache.camel.impl.engine.AbstractCamelContext.startServices(AbstractCamelContext.java:3081)
[2] 	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2763)
[2] 	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2662)
[2] 	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2625)
[2] 	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
[2] 	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2467)
[2] 	at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doStart(ApplicationRuntime.java:206)
[2] 	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
[2] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:83)
[2] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[2] 	at org.apache.camel.k.main.Application.main(Application.java:42)
[2] 2020-06-17 09:40:12.369 INFO  [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.
^CRun integration terminating
```

**Comment by nicolaferraro** [comment]
Let's keep this open until we merge changes in the `release-1.0.x` branch

**Comment by lburgazzoli** [comment]
@nicolaferraro has this been merged ?

**Comment by nicolaferraro** [comment]
Merged
