### ISSUE TITLE
Groovy example is broken

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1842]
File: examples/routes.groovy

Logs:

```
[1] 2020-12-03 16:41:56,092 WARN  [org.apa.cam.com.tim.TimerConsumer] (Camel (camel-1) thread #0 - timer://groovy) Error processing exchange. Exchange[19B282B64B1E822-0000000000000003]. Caused by: [groovy.lang.MissingPropertyException - No such property: DELEGATE_FIRST for class: org.apache.camel.k.loader.groovy.dsl.BeansConfiguration]: groovy.lang.MissingPropertyException: No such property: DELEGATE_FIRST for class: org.apache.camel.k.loader.groovy.dsl.BeansConfiguration
[1]     at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
[1]     at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:172)
[1]     at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
[1]     at org.apache.camel.k.loader.groovy.dsl.Support$Trait$Helper$_processor_closure1.doCall(Support.groovy:26)
[1]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[1]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[1]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1]     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[1]     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
[1]     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
[1]     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
[1]     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
[1]     at groovy.lang.Closure.call(Closure.java:412)
[1]     at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
[1]     at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:110)
[1]     at com.sun.proxy.$Proxy20.process(Unknown Source)
[1]     at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66)
[1]     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:404)
[1]     at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
[1]     at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
[1]     at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
[1]     at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:287)
[1]     at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:207)
[1]     at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
[1]     at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[1]     at java.base/java.util.TimerThread.run(Timer.java:506)

```

**Comment by lburgazzoli** [comment]
this should have been fixed in recent runtime

**Comment by nicolaferraro** [comment]
Fixed with latest runtime
