### ISSUE TITLE
[regression] panic: runtime error: invalid memory address or nil pointer dereference with version 1.3.0 when calling without or with - or -- arguments

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#1872]
- downloaded https://github.com/apache/camel-k/releases/download/v1.3.0/camel-k-client-1.3.0-linux-64bit.tar.gz
- extract
- call ./kamel

```
(base) [apupier@linux camel-k-client-1.3.0-linux-64bit]$ ./kamel
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18084b6]

goroutine 1 [running]:
github.com/spf13/cobra.(*Command).Name(0x0, 0xc0001181b0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:1258 +0x26
github.com/apache/camel-k/pkg/cmd.createKamelWithModelineCommand(0x2161020, 0xc0007bc540, 0xc0001181b0, 0x0, 0x0, 0xc0007b4df0, 0x1, 0xc0000cb2b0, 0x315fa00, 0x7f62a78e3108, ...)
	github.com/apache/camel-k/pkg/cmd/modeline.go:92 +0xf7
github.com/apache/camel-k/pkg/cmd.NewKamelWithModelineCommand(0x2161020, 0xc0007bc540, 0xc0001181b0, 0x1, 0x1, 0xc00014df48, 0x445efa, 0x30dbae0, 0xc000000180, 0xc00014df78, ...)
	github.com/apache/camel-k/pkg/cmd/modeline.go:64 +0x9b
main.main()
	github.com/apache/camel-k/cmd/kamel/main.go:45 +0x163
```

**Comment by apupier** [comment]
it occurs also when using `--` version of commands:
```
(base) [apupier@linux camel-k-client-1.3.0-linux-64bit]$ ./kamel --help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18084b6]

goroutine 1 [running]:
github.com/spf13/cobra.(*Command).Name(0x0, 0xc00000e070, 0x1)
	github.com/spf13/cobra@v1.0.0/command.go:1258 +0x26
github.com/apache/camel-k/pkg/cmd.createKamelWithModelineCommand(0x2161020, 0xc0006204c0, 0xc00000e070, 0x1, 0x1, 0xc00075c700, 0x1, 0xc0001a5c70, 0x315fa00, 0x7f3bcfcdf108, ...)
	github.com/apache/camel-k/pkg/cmd/modeline.go:92 +0xf7
github.com/apache/camel-k/pkg/cmd.NewKamelWithModelineCommand(0x2161020, 0xc0006204c0, 0xc00000e060, 0x2, 0x2, 0xc0000e3f48, 0x445efa, 0x30dbae0, 0xc000000180, 0xc0000e3f78, ...)
	github.com/apache/camel-k/pkg/cmd/modeline.go:64 +0x9b
main.main()
	github.com/apache/camel-k/cmd/kamel/main.go:45 +0x163

```

although `kamel help` is working fine

**Comment by apupier** [comment]
last line in kamel code is:

https://github.com/apache/camel-k/blame/cdc01968a9aeedcb9fc8a9238e96f9acfbe04f02/pkg/cmd/modeline.go#L92

not able to make the project working locally (was never abel to make any go project working yet) but suspecting that the target has no Parent? so target.Parent().name() is throwing this error?

**Comment by apupier** [comment]
I think that this issue should have the Milestone 1.3.1 set. https://github.com/apache/camel-k/commit/2d0a6f3435e0e3dcac613c0f7cff96ec5b78860d
