### ISSUE TITLE
Adding component dependency doesn't seem to work

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-k#1935]
Trying to run the following script `test.js` with the command `kamel run -d camel-undertow test.js` fails to build a kit.
```js
// camel-k: language=js
restConfiguration()
  .component("undertow")
  .contextPath("rest")
  .host("0.0.0.0")
  .port(9101);
rest("/undertow")
  .get("/hello").produces("application/json")
  .to("direct:hello");
from("direct:hello")
  .setBody(simple("hello"))
  .log("body = ${body}");
```

The operator got the following error:
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.apache.camel:camel-undertow:jar is missing. @ line 35, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.camel.k.integration:camel-k-integration:1.3.0 (/tmp/builder-947734287/maven/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.camel:camel-undertow:jar is missing. @ line 35, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by tadayosi** [comment]
Ah is it just that Camel Quarkus doesn't support camel-undertow yet?

**Comment by jamesnetherton** [comment]
Correct, camel-quarkus does not provide an extension for `camel-undertow` (and likely never will). There's no need to specify the component. IIRC it will use the platform-http component by default and leverage the in-built Quarkus HTTP server.

**Comment by tadayosi** [comment]
Thanks. But then without `-d camel-undertow` I get the following error at runtime of the `test` it pod:
```
2021-01-22 09:21:53,209 INFO  [org.apa.cam.k.Runtime] (main) Apache Camel K Runtime 1.6.0
2021-01-22 09:21:53,214 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-01-22 09:21:53,272 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='test', language='js', location='file:/etc/camel/sources/i-source-000/test.js', }
2021-01-22 09:21:54,986 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.7.0 (camel-1) is starting
2021-01-22 09:21:54,989 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) StreamCaching is not in use. If using streams then it's recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2021-01-22 09:21:54,995 ERROR [org.apa.cam.imp.eng.AbstractCamelContext] (main) Error starting CamelContext (camel-1) due to exception thrown: Failed to start route route2 because of null: org.apache.camel.FailedToStartRouteException: Failed to start route route2 because of null
	at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:122)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doWarmUpRoutes(InternalRouteStartupManager.java:270)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:157)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:115)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2889)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2702)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2665)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2431)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:75)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:120)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:774)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: undertow of type: org.apache.camel.spi.RestConsumerFactory
	at org.apache.camel.component.rest.RestEndpoint.createConsumer(RestEndpoint.java:483)
	at org.apache.camel.impl.engine.DefaultRoute.addServices(DefaultRoute.java:575)
	at org.apache.camel.impl.engine.DefaultRoute.onStartingServices(DefaultRoute.java:160)
	at org.apache.camel.impl.engine.RouteService.doWarmUp(RouteService.java:150)
	at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:120)
	... 22 more
```

**Comment by jamesnetherton** [comment]
Right, but you don't need the Undertow consumer. You can drop the `component`, `host` & `port` parts from `restConfiguration` and fallback on platform-http like in:

https://github.com/apache/camel-k/blob/master/examples/routes-rest.js

**Comment by tadayosi** [comment]
@jamesnetherton Ah yes!  Thanks. It works now. Closing.
