### ISSUE TITLE
Exposing Rest endpoint

### ISSUE THREAD

**Issue by shyabithd** [apache/camel-k#212]
Description: 

I tried to create a rest endpoint using camel-k however when DSL is deployed I got following error.
Should Camel-k download dependent components?

[2] Exception in thread "main" org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[rest:get:/hello?routeId=route1]] -> [To[... because of Cannot find RestConsumerFactory in Registry or as a Component to use
[2] 	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:147)
[2] 	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3949)
[2] 	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3856)
[2] 	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3642)
[2] 	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3494)
[2] 	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:209)
[2] 	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3253)
[2] 	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3249)
[2] 	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3272)
[2] 	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3249)
[2] 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
[2] 	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3165)
[2] 	at org.apache.camel.k.jvm.Runtime.doStart(Runtime.java:101)
[2] 	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
[2] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:170)
[2] 	at org.apache.camel.k.jvm.Application.main(Application.java:65)
[2] Caused by: java.lang.IllegalStateException: Cannot find RestConsumerFactory in Registry or as a Component to use
[2] 	at org.apache.camel.component.rest.RestEndpoint.createConsumer(RestEndpoint.java:526)
[2] 	at org.apache.camel.impl.EventDrivenConsumerRoute.addServices(EventDrivenConsumerRoute.java:69)
[2] 	at org.apache.camel.impl.DefaultRoute.onStartingServices(DefaultRoute.java:107)
[2] 	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:172)
[2] 	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145)

**Comment by lburgazzoli** [comment]
Can you post the full route ?

**Comment by lburgazzoli** [comment]
yes camel-k can do that :) we need to check the route to see if there are missing cases.

**Comment by shyabithd** [comment]
Hi @lburgazzoli,

Thank you for the quick response. 
This is just to get an idea how things work. Here is the route file.

import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;

public class RestTest extends RouteBuilder {
  @Override
  public void configure() throws Exception {
    restConfiguration().component("restlet").host("localhost").port("8080");
    rest().get("/hello").to("direct:hello");
    from("direct:hello").log(LoggingLevel.INFO, "Hello World").transform().simple("Hello World");
  }
}

**Comment by lburgazzoli** [comment]
will have a look, in the meantime you can try to add the restlet dependency like:

    kamel run -d camel:restlet ...

**Comment by nicolaferraro** [comment]
Yeah, I think current metadata discovery works with explicit uris (e.g. "undertow:http..."), we should make it more intelligent..

**Comment by shyabithd** [comment]
Hi yes it works with the inclusion of dependency. thanks.

**Comment by lburgazzoli** [comment]
sorry my mistake:

    kamel run --dependency=camel-restlet --dev runtime/examples/Rest.java

**Comment by shyabithd** [comment]
Hi @lburgazzoli - Another small question, After I deploy the DSL, I noticed that ingress does not create. Have you noticed an issue like that?

**Comment by nicolaferraro** [comment]
We're about to release v 0.0.5 that contains the generator for ingress.

**Comment by lburgazzoli** [comment]
@nicolaferraro I think we can close this one, right ?
