### ISSUE TITLE
`kamel` run fails for remote files on windows

### ISSUE THREAD

**Issue by heiko-braun** [apache/camel-k#2239]
```
 ./kamel run https://raw.githubusercontent.com/apache/camel-k/b29333f0a878d5d09fb3965be8fe586d77dd95d0/e2e/common/files/yaml.yaml
panic: runtime error: invalid memory address or nil pointer dereference[signal 0xc0000005 code=0x0 addr=0x18 pc=0x19ba09f]
goroutine 1 [running]:github.com/apache/camel-k/pkg/cmd.isLocal(0xc0000b2080, 0x74, 0x1) github.com/apache/camel-k@/pkg/cmd/run.go:653 +0x9fgithub.com/apache/camel-k/pkg/cmd.ResolveSources(0x21fdc40, 0xc0004f4140, 0xc000215c60, 0x1, 0x1, 0xc0003e6200, 0x2, 0x1b1b7a0, 0xc0000a1b80, 0x40c8f0, ...) github.com/apache/camel-k@/pkg/cmd/util_sources.go:68 +0xebgithub.com/apache/camel-k/pkg/cmd.extractModelineOptions(0x21fdc40, 0xc0004f4140, 0xc000215c60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0) github.com/apache/camel-k@/pkg/cmd/modeline.go:188 +0xa8github.com/apache/camel-k/pkg/cmd.createKamelWithModelineCommand(0x21fdc40, 0xc0004f4140, 0xc00007c090, 0x2, 0x3, 0xc000309920, 0x10, 0x1fbb548, 0x320f9a0, 0x180008, ...) github.com/apache/camel-k@/pkg/cmd/modeline.go:121 +0x3c0github.com/apache/camel-k/pkg/cmd.NewKamelWithModelineCommand(0x21fdc40, 0xc0004f4140, 0xc00007c080, 0x3, 0x4, 0x1fba6d0, 0x0, 0x0, 0xc0002f7b30, 0xc0000a1ef0, ...) github.com/apache/camel-k@/pkg/cmd/modeline.go:64 +0xa2main.main() github.com/apache/camel-k@/cmd/kamel/main.go:45 +0x19e 
```

**Comment by heiko-braun** [comment]
The same behaviour for `github` prefixed URL

```
./kamel run github:apache/camel-k/e2e/common/files/Java.java./kamel run github:apache/camel-k/e2e/common/files/Java.java
panic: runtime error: invalid memory address or nil pointer dereference[signal 0xc0000005 code=0x0 addr=0x18 pc=0x19ba09f]
goroutine 1 [running]:github.com/apache/camel-k/pkg/cmd.isLocal(0xc000048330, 0x30, 0x1) github.com/apache/camel-k@/pkg/cmd/run.go:653 +0x9fgithub.com/apache/camel-k/pkg/cmd.ResolveSources(0x21fdc40, 0xc000505800, 0xc00057c900, 0x1, 0x1, 0xc00049b200, 0x2, 0x1b1b7a0, 0xc0000a5b80, 0x40c8f0, ...) github.com/apache/camel-k@/pkg/cmd/util_sources.go:68 +0xebgithub.com/apache/camel-k/pkg/cmd.extractModelineOptions(0x21fdc40, 0xc000505800, 0xc00057c900, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0) github.com/apache/camel-k@/pkg/cmd/modeline.go:188 +0xa8github.com/apache/camel-k/pkg/cmd.createKamelWithModelineCommand(0x21fdc40, 0xc000505800, 0xc00007c090, 0x2, 0x3, 0xc00057c060, 0x10, 0x1fbb548, 0x320f9a0, 0x180008, ...) github.com/apache/camel-k@/pkg/cmd/modeline.go:121 +0x3c0github.com/apache/camel-k/pkg/cmd.NewKamelWithModelineCommand(0x21fdc40, 0xc000505800, 0xc00007c080, 0x3, 0x4, 0x1fba6d0, 0x0, 0x0, 0xc000162900, 0xc0000a5ef0, ...) github.com/apache/camel-k@/pkg/cmd/modeline.go:64 +0xa2main.main() github.com/apache/camel-k@/cmd/kamel/main.go:45 +0x19e 
```

**Comment by heiko-braun** [comment]
@bouskaJ FYI

**Comment by squakez** [comment]
I think the problem is here: https://github.com/apache/camel-k/blob/6904f9593183765af83d86912cf5d7f38888f9a3/pkg/cmd/run.go#L683-L689. We only check the error if the file does not exist. If any other kind of errors arise, then we have a `nil` for the `info` and it's likely what's happening here for Windows. I can try to reproduce a similar situation on a `linux` or alternatively remove the dust off some `windows` machine in the attic.
