### ISSUE TITLE
Groovy script JSON paring runs into java.util.ServiceConfigurationError: org.apache.groovy.json.FastStringServiceFactory: org.apache.groovy.json.DefaultFastStringServiceFactory not a subtype

### ISSUE THREAD

**Issue by catshout** [apache/camel-k#2418]
We're using Camel-K 1.4.0 on a GCP k8s service.

The following route

```
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://camel.apache.org/schema/spring"
        xsi:schemaLocation="
        http://camel.apache.org/schema/spring
        http://camel.apache.org/schema/spring/camel-spring.xsd">
   <route>
      <from uri="timer:timer?repeatCount=1"/>
      <setBody>
         <constant>
            {"GTIN":"4001724819004","ProductNo":"GSIN43062860077950","ArticleNo":"430628600779500001","StoreID":"12","PartnerID":"METRO","PriceType":"AKT_B2C","ValidFrom":"28.03.2019","ValidTo":"03.04.2019","Price":"1,70","Currency":"EUR","VAT":"7","BasePrice":"0,53","BasePriceUnit":"g","BasePriceAmount":"100","Active":"1","Updated":"02.07.2020","BaseAmount":"1","ValidPromoPrice":"","PurchasePrice":"1,59"}
         </constant>
      </setBody>
      <to uri="log:info"/>
      <setBody>
         <groovy>
            import groovy.json.JsonSlurper
            import groovy.xml.MarkupBuilder
            def xml = new JsonSlurper().parseText(request.body).with { json ->
            new java.io.StringWriter().with { sw ->
            new groovy.xml.MarkupBuilder(sw).article() {
            gtin(json.GTIN)
            productNumber(json.ProductNo)
            articleNumber(json.ArticleNo)
            storeId(json.StoreID)
            price(json.Price)
            }
            sw.toString().replaceAll(System.lineSeparator(),"")
            }
            }
            response = xml
         </groovy>
      </setBody>
      <to uri="log:info"/>
   </route>
</routes>
```

started with

```
kamel run helloGroovy.xml --dev -n camel-k -d mvn:org.codehaus.groovy:groovy-json:3.0.3 -d mvn:org.codehaus.groovy:groovy-xml:3.0.3
```

runs into an error

```
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[0B25F784644BEC2-0000000000000000]
[1]     at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
[1]     at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:564)
[1]     at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
[1]     at org.apache.camel.processor.SetPropertyProcessor.process(SetPropertyProcessor.java:58)
[1]     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:439)
[1]     at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
[1]     at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:62)
[1]     at org.apache.camel.processor.Pipeline.process(Pipeline.java:167)
[1]     at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:388)
[1]     at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:209)
[1]     at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
[1]     at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[1]     at java.base/java.util.TimerThread.run(Timer.java:506)
[1] Caused by: java.util.ServiceConfigurationError: org.apache.groovy.json.FastStringServiceFactory: org.apache.groovy.json.DefaultFastStringServiceFactory not a subtype
[1]     at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
[1]     at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
[1]     at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
[1]     at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
[1]     at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
[1]     at org.apache.groovy.json.internal.FastStringUtils$ServiceHolder.loadService(FastStringUtils.java:42)
[1]     at org.apache.groovy.json.internal.FastStringUtils$ServiceHolder.<clinit>(FastStringUtils.java:33)
[1]     at org.apache.groovy.json.internal.FastStringUtils.getService(FastStringUtils.java:56)
[1]     at org.apache.groovy.json.internal.FastStringUtils.toCharArray(FastStringUtils.java:67)
[1]     at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:112)
[1]     at groovy.json.JsonSlurper.parseText(JsonSlurper.java:202)
[1]     at groovy.json.JsonSlurper$parseText.call(Unknown Source)
[1]     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[1]     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[1]     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
[1]     at Script_65dcaa17bc1b80f6d63382ad593b3d36.run(Script_65dcaa17bc1b80f6d63382ad593b3d36.groovy:22)
[1]     at org.apache.camel.language.groovy.GroovyExpression.evaluate(GroovyExpression.java:52)
[1]     at org.apache.camel.processor.SetPropertyProcessor.process(SetPropertyProcessor.java:47)
[1]     ... 9 more
```

The same route runs properly with Camel 3.9.0 on Karaf 4.2.9.

**Comment by lburgazzoli** [comment]
@catshout can you provide the dependencies resolved by camel-k for this integration ? they should be listed in the integration kit associated to the integration

**Comment by catshout** [comment]
@lburgazzoli could you please give me a hint how to figure this out?

**Comment by lburgazzoli** [comment]
So every integration has a reference to an IntegrationKit (there should be a kit or integrationKit field in the integration status).

Then
  
  kubectl get integrationkit ${integrtion-kit-name} -o yaml

**Comment by catshout** [comment]
Voilà

```
apiVersion: camel.apache.org/v1
kind: IntegrationKit
metadata:
  creationTimestamp: "2021-06-17T17:52:10Z"
  generation: 1
  labels:
    camel.apache.org/created.by.kind: Integration
    camel.apache.org/created.by.name: hello-groovy
    camel.apache.org/created.by.namespace: camel-k
    camel.apache.org/created.by.version: "24038360"
    camel.apache.org/kit.type: platform
    camel.apache.org/runtime.provider: quarkus
    camel.apache.org/runtime.version: 1.7.0
  managedFields:
  - apiVersion: camel.apache.org/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:camel.apache.org/created.by.kind: {}
          f:camel.apache.org/created.by.name: {}
          f:camel.apache.org/created.by.namespace: {}
          f:camel.apache.org/created.by.version: {}
          f:camel.apache.org/kit.type: {}
          f:camel.apache.org/runtime.provider: {}
          f:camel.apache.org/runtime.version: {}
      f:spec:
        .: {}
        f:dependencies: {}
      f:status:
        .: {}
        f:conditions: {}
        f:digest: {}
        f:phase: {}
        f:platform: {}
        f:runtimeProvider: {}
        f:runtimeVersion: {}
        f:version: {}
    manager: kamel
    operation: Update
    time: "2021-06-17T17:52:10Z"
  name: kit-c35onii97unrcov6oak0
  namespace: camel-k
  resourceVersion: "24038376"
  selfLink: /apis/camel.apache.org/v1/namespaces/camel-k/integrationkits/kit-c35onii97unrcov6oak0
  uid: 006268b0-88e8-453e-af28-d11783a6f281
spec:
  dependencies:
  - camel:core
  - camel:groovy
  - camel:log
  - camel:timer
  - mvn:org.apache.camel.k:camel-k-runtime
  - mvn:org.apache.camel.quarkus:camel-quarkus-xml-io-dsl
  - mvn:org.codehaus.groovy:groovy-json:3.0.3
  - mvn:org.codehaus.groovy:groovy-xml:3.0.3
status:
  conditions:
  - lastTransitionTime: "2021-06-17T17:52:10Z"
    lastUpdateTime: "2021-06-17T17:52:10Z"
    message: IntegrationPlatform (camel-k)
    reason: IntegrationPlatformAvailable
    status: "True"
    type: IntegrationPlatformAvailable
  digest: vv0yvhZUKFPlBV1dXnrbx-LDN4AOOLKyd68ZBkVgohVs
  phase: Build Running
  platform: camel-k
  runtimeProvider: quarkus
  runtimeVersion: 1.7.0
  version: 1.4.0
```

**Comment by lburgazzoli** [comment]
@catshout the status should contains also an "artifacts" section, something like:

```
status:
  artifacts:
  - checksum: sha1:E3GkEG6R3dM6cC16WNLuXYatTgc=
    id: camel-k-integration-1.4.0.jar
    target: dependencies/app/camel-k-integration-1.4.0.jar
  - checksum: sha1:MO+/eeSitvTaqztL8EK7h2BT5W4=
    id: io.quarkus.quarkus-bootstrap-runner-1.13.0.Final.jar
    target: dependencies/lib/boot/io.quarkus.quarkus-bootstrap-runner-1.13.0.Final.jar
```

can you add that too ?

**Comment by catshout** [comment]
@lburgazzoli sorry, I missed these parts, have added the full output

**Comment by lburgazzoli** [comment]
ok, do you mind trying with groovy 3.0.5 ?

```
-d mvn:org.codehaus.groovy:groovy-json:3.0.5 -d mvn:org.codehaus.groovy:groovy-xml:3.0.5
```

I got strange result when different versions of groovy where on the classpath.

BTW, I think the issue should have been solved in the latest releases as I'm not able to reproduce it with the latest camel-k-runtime (see as example, https://github.com/lburgazzoli/camel-k-runtime-example-xml).

But we'll add an integration test for this

**Comment by catshout** [comment]
@lburgazzoli I've tried with groovy 3.0.5, same result unfortunately. Is this possible to get a newer camel-k on our cluster to test this as well?
