### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when running a simple integration

### ISSUE THREAD

**Issue by clabautdidier** [apache/camel-k#2697]
I'm trying camel-k 1.6.0 on our Openshift v1.8 development environment.

I want to experiment with kamelets and bindings. 

What I'm trying to do is create a first flow from rest to a Kafka topic, and then a second flow from the topic to the log.

I created a kafka-sink kamelet for the first flow and a kafka-source kamelet for the second flow. The first flow I implemented using a simple Groovy script:

```
rest("/kafkamelet")`
        .put()`
        .to("kamelet:kafka-sink?bootstrapServers={{kafka.host}}:{{kafka.port}}&topic={{consumer.topic}}");`
```

And is deployed via the command `kamel run .\rest-to-kafka-kamelet.groovy --config configmap:kafka.props `

This part is fine, I get a rest service with endpoint path /kafkamelet that writes the contents of the PUT request to the topic in the config map.

For the second flow I tried both another Groovy script and a binding yaml. Both result in the Camel-k operator crashing with the memory error.

The binding file I use is this one:

```
  apiVersion: camel.apache.org/v1alpha1 
  kind: KameletBinding  
  metadata:  
    name: kafka-to-log-binding
    annotations:
      trait.camel.apache.org/logging.level: DEBUG
      trait.camel.apache.org/logging.color: "false"
  spec:
    source:
      ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: kafka-source-kamelet
      properties:
        bootstrapServers: "xx.xx.xx.xx:9092"
        topic: "demoTopic"
    sink:
      ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: log-sink
```

(I replaced the actual ip address with xx.xx.xx.xx)

The groovy file is as follows:
```
from("kamelet:kafka-source-kamelet?bootstrapServers={{kafka.host}}:{{kafka.port}}&topic={{consumer.topic}}")
        .to('log:info')
```

When I "kamel run" any of these, the operator starts building, and then crashes with the last lines in the log shown below:
```
{"level":"info","ts":1634391161.246974,"logger":"camel-k.maven.build","msg":"------------------------------------------------------------------------"}
{"level":"info","ts":1634391161.2470095,"logger":"camel-k.maven.build","msg":"BUILD SUCCESS"}
{"level":"info","ts":1634391161.2471273,"logger":"camel-k.maven.build","msg":"------------------------------------------------------------------------"}
{"level":"info","ts":1634391161.2495575,"logger":"camel-k.maven.build","msg":"Total time:  21.312 s"}
{"level":"info","ts":1634391161.2498348,"logger":"camel-k.maven.build","msg":"Finished at: 2021-10-16T13:32:41Z"}
{"level":"info","ts":1634391161.2499456,"logger":"camel-k.maven.build","msg":"------------------------------------------------------------------------"}
{"level":"info","ts":1634391161.2909498,"logger":"camel-k.builder","msg":"step done in 22.752703 seconds","step":"github.com/apache/camel-k/pkg/builder/BuildQuarkusRunner","phase":"20","task":"builder"}
{"level":"info","ts":1634391161.2909875,"logger":"camel-k.builder","msg":"executing step","step":"github.com/apache/camel-k/pkg/builder/ComputeQuarkusDependencies","phase":"21","task":"builder"}
{"level":"info","ts":1634391161.353529,"logger":"camel-k.builder","msg":"step done in 0.062527 seconds","step":"github.com/apache/camel-k/pkg/builder/ComputeQuarkusDependencies","phase":"21","task":"builder"}
{"level":"info","ts":1634391161.3535652,"logger":"camel-k.builder","msg":"executing step","step":"github.com/apache/camel-k/pkg/builder/IncrementalImageContext","phase":"30","task":"builder"}
{"level":"info","ts":1634391161.367313,"logger":"camel-k.builder","msg":"step done in 0.013734 seconds","step":"github.com/apache/camel-k/pkg/builder/IncrementalImageContext","phase":"30","task":"builder"}
{"level":"info","ts":1634391161.3673422,"logger":"camel-k.builder","msg":"dependencies: [camel:kafka camel:kamelet camel:log mvn:io.quarkus:quarkus-logging-json mvn:org.apache.camel.k:camel-k-runtime mvn:org.apache.camel.quarkus:camel-quarkus-groovy-dsl mvn:org.apache.camel.quarkus:camel-quarkus-yaml-dsl]"}
{"level":"info","ts":1634391161.3673897,"logger":"camel-k.builder","msg":"artifacts: [camel-k-integration-1.6.0.jar io.quarkus.quarkus-bootstrap-runner-2.2.0.Final.jar io.quarkus.quarkus-development-mode-spi-2.2.0.Final.jar io.smallrye.common.smallrye-common-io-1.6.0.jar org.glassfish.jakarta.json-1.1.6.jar org.graalvm.sdk.graal-sdk-21.2.0.jar org.jboss.logging.jboss-logging-3.4.2.Final.jar org.jboss.logmanager.jboss-logmanager-embedded-1.0.9.jar org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar com.fasterxml.jackson.core.jackson-annotations-2.12.4.jar com.fasterxml.jackson.core.jackson-core-2.12.4.jar com.fasterxml.jackson.core.jackson-databind-2.12.4.jar com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.12.4.jar com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.12.4.jar com.fasterxml.jackson.module.jackson-module-parameter-names-2.12.4.jar com.github.ben-manes.caffeine.caffeine-2.9.2.jar com.github.luben.zstd-jni-1.4.9-1.jar com.google.errorprone.error_prone_annotations-2.2.0.jar io.quarkus.arc.arc-2.2.0.Final.jar io.quarkus.quarkus-arc-2.2.0.Final.jar io.quarkus.quarkus-caffeine-2.2.0.Final.jar io.quarkus.quarkus-core-2.2.0.Final.jar io.quarkus.quarkus-jackson-2.2.0.Final.jar io.quarkus.quarkus-jsonp-2.2.0.Final.jar io.quarkus.quarkus-kafka-client-2.2.0.Final.jar io.quarkus.quarkus-logging-json-2.2.0.Final.jar io.smallrye.common.smallrye-common-annotation-1.6.0.jar io.smallrye.common.smallrye-common-classloader-1.6.0.jar io.smallrye.common.smallrye-common-constraint-1.6.0.jar io.smallrye.common.smallrye-common-expression-1.6.0.jar io.smallrye.common.smallrye-common-function-1.6.0.jar io.smallrye.config.smallrye-config-2.4.4.jar io.smallrye.config.smallrye-config-common-2.4.4.jar io.smallrye.config.smallrye-config-core-2.4.4.jar jakarta.annotation.jakarta.annotation-api-1.3.5.jar jakarta.el.jakarta.el-api-3.0.3.jar jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar jakarta.inject.jakarta.inject-api-1.0.jar jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar jakarta.transaction.jakarta.transaction-api-1.3.3.jar org.apache.camel.camel-api-3.11.1.jar org.apache.camel.camel-base-3.11.1.jar org.apache.camel.camel-base-engine-3.11.1.jar org.apache.camel.camel-bean-3.11.1.jar org.apache.camel.camel-componentdsl-3.11.1.jar org.apache.camel.camel-core-catalog-3.11.1.jar org.apache.camel.camel-core-engine-3.11.1.jar org.apache.camel.camel-core-languages-3.11.1.jar org.apache.camel.camel-core-model-3.11.1.jar org.apache.camel.camel-core-processor-3.11.1.jar org.apache.camel.camel-core-reifier-3.11.1.jar org.apache.camel.camel-dsl-support-3.11.1.jar org.apache.camel.camel-endpointdsl-3.11.1.jar org.apache.camel.camel-groovy-dsl-3.11.1.jar org.apache.camel.camel-groovy-dsl-common-3.11.1.jar org.apache.camel.camel-kafka-3.11.1.jar org.apache.camel.camel-kamelet-3.11.1.jar org.apache.camel.camel-log-3.11.1.jar org.apache.camel.camel-main-3.11.1.jar org.apache.camel.camel-management-api-3.11.1.jar org.apache.camel.camel-microprofile-config-3.11.1.jar org.apache.camel.camel-support-3.11.1.jar org.apache.camel.camel-tooling-model-3.11.1.jar org.apache.camel.camel-util-3.11.1.jar org.apache.camel.camel-util-json-3.11.1.jar org.apache.camel.camel-yaml-dsl-3.11.1.jar org.apache.camel.camel-yaml-dsl-common-3.11.1.jar org.apache.camel.camel-yaml-dsl-deserializers-3.11.1.jar org.apache.camel.k.camel-k-core-1.9.0.jar org.apache.camel.k.camel-k-core-api-1.9.0.jar org.apache.camel.k.camel-k-core-support-1.9.0.jar org.apache.camel.k.camel-k-runtime-1.9.0.jar org.apache.camel.quarkus.camel-quarkus-bean-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-core-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-groovy-dsl-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-kafka-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-kamelet-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-log-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-support-common-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-yaml-dsl-2.2.0.jar org.apache.kafka.kafka-clients-2.8.0.jar org.codehaus.groovy.groovy-3.0.8.jar org.eclipse.microprofile.config.microprofile-config-api-2.0.jar org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.2.jar org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar org.jboss.threads.jboss-threads-3.4.2.Final.jar org.lz4.lz4-java-1.6.0.jar org.slf4j.slf4j-api-1.7.30.jar org.snakeyaml.snakeyaml-engine-2.3.jar org.xerial.snappy.snappy-java-1.1.8.1.jar generated-bytecode.jar quarkus-application.dat quarkus-app-dependencies.txt quarkus-run.jar]"}
{"level":"info","ts":1634391161.3674443,"logger":"camel-k.builder","msg":"artifacts selected: [camel-k-integration-1.6.0.jar com.fasterxml.jackson.core.jackson-annotations-2.12.4.jar com.fasterxml.jackson.core.jackson-core-2.12.4.jar com.fasterxml.jackson.core.jackson-databind-2.12.4.jar com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.12.4.jar com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.12.4.jar com.fasterxml.jackson.module.jackson-module-parameter-names-2.12.4.jar com.github.ben-manes.caffeine.caffeine-2.9.2.jar com.github.luben.zstd-jni-1.4.9-1.jar com.google.errorprone.error_prone_annotations-2.2.0.jar io.quarkus.quarkus-caffeine-2.2.0.Final.jar io.quarkus.quarkus-jackson-2.2.0.Final.jar io.quarkus.quarkus-kafka-client-2.2.0.Final.jar org.apache.camel.camel-kafka-3.11.1.jar org.apache.camel.camel-kamelet-3.11.1.jar org.apache.camel.camel-yaml-dsl-3.11.1.jar org.apache.camel.camel-yaml-dsl-common-3.11.1.jar org.apache.camel.camel-yaml-dsl-deserializers-3.11.1.jar org.apache.camel.quarkus.camel-quarkus-kafka-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-kamelet-2.2.0.jar org.apache.camel.quarkus.camel-quarkus-yaml-dsl-2.2.0.jar org.apache.kafka.kafka-clients-2.8.0.jar org.lz4.lz4-java-1.6.0.jar org.snakeyaml.snakeyaml-engine-2.3.jar org.xerial.snappy.snappy-java-1.1.8.1.jar generated-bytecode.jar quarkus-application.dat quarkus-app-dependencies.txt quarkus-run.jar]"}
{"level":"info","ts":1634391161.367455,"logger":"camel-k.builder","msg":"base image: "}
{"level":"info","ts":1634391161.3674579,"logger":"camel-k.builder","msg":"resolved base image: image-registry.openshift-image-registry.svc:5000/camel-k-didier/camel-k-kit-c5lbk812g0rl8e5cq73g@sha256:869bd1203354899d7ab3246ee3d2fbf2ab1b32e8a0f9ce13b7cb626ecc3b9ae5"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x90cf82]

goroutine 1967 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc0004aef50, 0x2121b00, 0x2810860, 0xc00189a500, 0x0, 0x0, 0x24140c0, 0xc00189a500, 0x287dfa0, 0x24140c0)
	k8s.io/apimachinery@v0.20.2/pkg/runtime/scheme.go:481 +0x2a2
k8s.io/apimachinery/pkg/runtime.(*Scheme).UnsafeConvertToVersion(...)
	k8s.io/apimachinery@v0.20.2/pkg/runtime/scheme.go:447
k8s.io/apimachinery/pkg/runtime.unsafeObjectConvertor.ConvertToVersion(0xc0004aef50, 0x2810860, 0xc00189a500, 0x0, 0x0, 0x0, 0x0, 0x2810860, 0xc00189a500)
	k8s.io/apimachinery@v0.20.2/pkg/runtime/helper.go:39 +0x5f
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc00189a280, 0xc0012ab800, 0x125, 0x600, 0xc000a43fb0, 0x0, 0x0, 0xc0012ab800, 0x125, 0x600, ...)
	k8s.io/apimachinery@v0.20.2/pkg/runtime/serializer/versioning/versioning.go:171 +0x362
k8s.io/client-go/rest.Result.Error(0xc0012ab800, 0x125, 0x600, 0x0, 0x0, 0x0, 0xc001e99790, 0x10, 0x27f6dc0, 0xc00189a460, ...)
	k8s.io/client-go@v0.20.2/rest/request.go:1309 +0x10e
github.com/apache/camel-k/pkg/builder.(*s2iTask).Do(0xc001505600, 0x2849aa0, 0xc00034c3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/apache/camel-k/pkg/builder/s2i.go:182 +0xc18
github.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild(0xc001aa51a0, 0xc00068b200)
	github.com/apache/camel-k/pkg/controller/build/monitor_routine.go:146 +0x46a
created by github.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).Handle
	github.com/apache/camel-k/pkg/controller/build/monitor_routine.go:77 +0x417`
```

Is there any way I can see in more detail what is going on?

**Comment by squakez** [comment]
Hello, can you confirm the name of the source Kamelet you're using is `kafka-source-kamelet`? If you were willing to use the Kamelet provided by the Catalog, then it should be `kafka-source`. If that is new Kamelet you provided, would you mind posting the configuration of that Kamelet please? (ie, `k get kafka-source-kamelet -o yaml`)

**Comment by oscerd** [comment]
I personally never faced something like that error before. Can you try with the original kamelet from the catalog?
