### ISSUE TITLE
Kamel run -o incompatible with --dev

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3195]
Running
```
kamel run ./examples/languages/Sample.java --dev -o yaml
```
Will produce an error like
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1d9b80f]

goroutine 1 [running]:
github.com/apache/camel-k/pkg/util/watch.HandleIntegrationStateChanges(0x2748458, 0xc000064280, 0x27829a0, 0xc0007f86c0, 0x0, 0xc000bb34c8, 0x0, 0x0, 0x0)
	github.com/apache/camel-k/pkg/util/watch/watch.go:35 +0x8f
github.com/apache/camel-k/pkg/cmd.(*runCmdOptions).waitForIntegrationReady(0xc000af0e00, 0xc00081b900, 0x27829a0, 0xc0007f86c0, 0x0, 0xc0007f86c0, 0x0, 0xc000848010)
	github.com/apache/camel-k/pkg/cmd/run.go:416 +0x9e
github.com/apache/camel-k/pkg/cmd.(*runCmdOptions).run(0xc000af0e00, 0xc00081b900, 0xc00044b2c0, 0x1, 0x4, 0x0, 0x0)
	github.com/apache/camel-k/pkg/cmd/run.go:343 +0x4be
github.com/spf13/cobra.(*Command).execute(0xc00081b900, 0xc00044b280, 0x4, 0x4, 0xc00081b900, 0xc00044b280)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00081ac80, 0xc0007f9b80, 0xc00004c1e0, 0x6)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/apache/camel-k/cmd/kamel/main.go:47 +0x17d
```
We probably need to include a check to warn the user the two options are not compatible.

**Comment by KuthumiPepple** [comment]
I'd like to be assigned this issue

**Comment by KuthumiPepple** [comment]
Hi, just wanted to check if this PR is ok to be merged or if there are more things to be done.

**Comment by squakez** [comment]
Yeah, it's good to go. Let's give the previous failing test another chance and then we can get it merged, thanks!

**Comment by oscerd** [comment]
I'm going to release 1.9.0 tomorrow, so eventually I could merge this immediately before releasing.
