### ISSUE TITLE
Yaml sources failure in 1.9.0

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3255]
I'm running locally some simple KameletBinding, ie `kamel bind timer:foo log:bar` and I am getting the following runtime error:
```
[1] 2022-05-05 10:36:15,625 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.dsl.yaml.common.exception.UnsupportedFieldException: Unsupported field (steps) for node: <org.snakeyaml.engine.v2.nodes.MappingNode (tag=tag:yaml.org,2002:map, values={ key=<org.snakeyaml.engine.v2.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=from)>; value=1752535057 }{ key=<org.snakeyaml.engine.v2.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=id)>; value=<NodeTuple keyNode=<org.snakeyaml.engine.v2.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=id)>; valueNode=<org.snakeyaml.engine.v2.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=binding)>> }{ key=<org.snakeyaml.engine.v2.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=steps)>; value=1649847375 })>
[1] 	at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:96)
[1] 	at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:33)
[1] 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:60)
[1] 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:231)
[1] 	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configuration(YamlRoutesBuilderLoader.java:226)
[1] 	at org.apache.camel.builder.RouteConfigurationBuilder.addRouteConfigurationsToCamelContext(RouteConfigurationBuilder.java:77)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutesConfigurations(AbstractCamelContext.java:1184)
[1] 	at org.apache.camel.main.RoutesConfigurer.addDiscoveredRoutes(RoutesConfigurer.java:232)
[1] 	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:213)
[1] 	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
[1] 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:590)
[1] 	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
[1] 	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
[1] 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
[1] 	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
[1] 	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
[1] 	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
[1] 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
[1] 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
[1] 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
[1] 	at io.quarkus.runtime.Application.start(Application.java:101)
[1] 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
[1] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
[1] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
[1] 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
[1] 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
[1] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[1] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[1] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[1] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
[1] 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

**Comment by squakez** [comment]
@oscerd I'm having a look at this, I think we need to have this solved before releasing 1.9.1. I have the feeling it is not working for yaml sources using `steps` for some reason.

**Comment by squakez** [comment]
The problem looks to be in how we're generating the source in the integration:
```
    generatedSources:
    - content: |
        - route:
            from:
              uri: timer:foo
            id: binding
            steps:
            - to: log:bar
```
Must `steps` be a child of the `from`!?

**Comment by davsclaus** [comment]
Yes see
https://camel.apache.org/manual/camel-3x-upgrade-guide-3_15.html#_camel_yaml_dsl

**Comment by squakez** [comment]
Okey, thanks for confirming @davsclaus - I'll see what exactly needed to fix here then.

**Comment by oscerd** [comment]
Are we fine to release 1.9.1?

**Comment by squakez** [comment]
@oscerd those failures are fixed. However we have a couple of problems still, ie, upgrade and an health metrics failure. If we are in a hurry, I guess we can do that and take care in parallel. If we can delay some more day, we may try to have them fixed before.

**Comment by squakez** [comment]
These are the failures: #3258 and #3261
