### ISSUE TITLE
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]

### ISSUE THREAD

**Issue by unionstars** [apache/camel-k#3969]
Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45) ~[camel-api-3.14.7.jar:3.14.7]
	at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:687) ~[camel-support-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:587) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:414) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at com.jd.openplat.core.service.MapperParseService.parse(MapperParseService.java:78) ~[classes/:na]
	... 54 common frames omitted
Caused by: io.atlasmap.api.AtlasException: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x4c
 at [Source: (GZIPInputStream); line: 1, column: 24570] (through reference chain: io.atlasmap.v2.ADMDigest["exportBlockData"]->java.lang.Object[][0]->io.atlasmap.v2.ValueContainer["value"])
	at io.atlasmap.core.ADMArchiveHandler.getDataSourceMetadataMap(ADMArchiveHandler.java:327) ~[atlas-core-2.3.1.jar:2.3.1]
	at io.atlasmap.core.DefaultAtlasContext.<init>(DefaultAtlasContext.java:117) ~[atlas-core-2.3.1.jar:2.3.1]
	at io.atlasmap.core.DefaultAtlasContextFactory.createContext(DefaultAtlasContextFactory.java:212) ~[atlas-core-2.3.1.jar:2.3.1]
	at io.atlasmap.core.DefaultAtlasContextFactory.createContext(DefaultAtlasContextFactory.java:54) ~[atlas-core-2.3.1.jar:2.3.1]
	at org.apache.camel.component.atlasmap.AtlasMapEndpoint.getOrCreateAtlasContext(AtlasMapEndpoint.java:246) ~[camel-atlasmap-3.14.7.jar:3.14.7]
	at org.apache.camel.component.atlasmap.AtlasMapEndpoint.onExchange(AtlasMapEndpoint.java:191) ~[camel-atlasmap-3.14.7.jar:3.14.7]
	at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:61) ~[camel-support-3.14.7.jar:3.14.7]
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66) ~[camel-support-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:217) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:199) ~[camel-support-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172) ~[camel-base-engine-3.14.7.jar:3.14.7]
	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:413) ~[camel-base-engine-3.14.7.jar:3.14.7]
	... 55 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x4c
 at [Source: (GZIPInputStream); line: 1, column: 24570] (through reference chain: io.atlasmap.v2.ADMDigest["exportBlockData"]->java.lang.Object[][0]->io.atlasmap.v2.ValueContainer["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:356) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1726) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3505) ~[jackson-databind-2.11.3.jar:2.11.3]
	at io.atlasmap.core.ADMArchiveHandler.getDataSourceMetadataMap(ADMArchiveHandler.java:315) ~[atlas-core-2.3.1.jar:2.3.1]
	... 70 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x4c
 at [Source: (GZIPInputStream); line: 1, column: 24570]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3605) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3612) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_2(UTF8StreamJsonParser.java:3385) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2514) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2466) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:297) ~[jackson-core-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:35) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.11.3.jar:2.11.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293) ~[jackson-databind-2.11.3.jar:2.11.3]
	... 79 common frames omitted

**Comment by squakez** [comment]
Thanks for reporting but we need a bit more of information to understand what kind of problem you're experiencing. Please, provide us:
1. The Camel K version you're using
2. a reproducer such as the route and the command used to run it
