### ISSUE TITLE
TestKamelReset test flakiness

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4316]
Recently, the test has becoming unstable:

```
  Integration "promote-route" updated
  Promoted Integration "promote-route" updated
❌ TestKamelReset (0s)
  OLM is not available in the cluster. Fallback to regular installation.
  Using storage class "standard" to create "camel-k-pvc" volume for the operator
  Camel K installed in namespace test-7ec13109-10fd-43c8-b9a0-d234a8a99c18 
❌ TestKamelReset/Reset_the_whole_platform (0s)
  No IntegrationPlatform resource in test-7ec13109-10fd-43c8-b9a0-d234a8a99c18 namespace
  Integration "yaml1" created
  panic: test timed out after 1h0m0s
  
  goroutine 13887 [running]:
  testing.(*M).startAlarm.func1()
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:2029 +0x8e
  created by time.goFunc
  	/opt/hostedtoolcache/go/1.18.10/x64/src/time/sleep.go:176 +0x32
  
  goroutine 1 [chan receive]:
  testing.(*T).Run(0xc0002236c0, {0x23dbb68?, 0x5222e5?}, 0x256a868)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
  testing.runTests.func1(0xc0004cf980?)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1839 +0x6e
  testing.tRunner(0xc0002236c0, 0xc000847cd8)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
  testing.runTests(0xc000134640?, {0x3afa240, 0x11, 0x11}, {0x7fb599007108?, 0x40?, 0x3b2e400?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1837 +0x457
  testing.(*M).Run(0xc000134640)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1719 +0x5d9
  main.main()
  	_testmain.go:79 +0x1aa
  
  goroutine 33 [select]:
  go.opencensus.io/stats/view.(*worker).start(0xc0000be700)
  	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
  created by go.opencensus.io/stats/view.init.0
  	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d
  
  goroutine 34 [chan receive, 60 minutes]:
  knative.dev/pkg/metrics.(*metricsWorker).start(0xc00047ea10)
  	/home/runner/go/pkg/mod/knative.dev/pkg@v0.0.0-20221123011842-b78020c16606/metrics/metrics_worker.go:99 +0x2f
  created by knative.dev/pkg/metrics.init.0
  	/home/runner/go/pkg/mod/knative.dev/pkg@v0.0.0-20221123011842-b78020c16606/metrics/exporter.go:39 +0xae
  
  goroutine 40 [IO wait]:
  internal/poll.runtime_pollWait(0x7fb570305198, 0x72)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0x89
  internal/poll.(*pollDesc).wait(0xc000342500?, 0xc000cdc000?, 0x0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
  internal/poll.(*pollDesc).waitRead(...)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
  internal/poll.(*FD).Read(0xc000342500, {0xc000cdc000, 0xc4ba, 0xc4ba})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x25a
  net.(*netFD).Read(0xc000342500, {0xc000cdc000?, 0xc00097e300?, 0xc000cdc049?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x29
  net.(*conn).Read(0xc0009f0020, {0xc000cdc000?, 0x7fb5726d5fff?, 0x7fb572534000?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x45
  crypto/tls.(*atLeastReader).Read(0xc0009a4fa8, {0xc000cdc000?, 0x0?, 0x140?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:785 +0x3d
  bytes.(*Buffer).ReadFrom(0xc0003cd3f8, {0x279e800, 0xc0009a4fa8})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/buffer.go:204 +0x98
  crypto/tls.(*Conn).readFromUntil(0xc0003cd180, {0x27a3d40?, 0xc0009f0020}, 0xc476?)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:807 +0xe5
  crypto/tls.(*Conn).readRecordOrCCS(0xc0003cd180, 0x0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:614 +0x116
  crypto/tls.(*Conn).readRecord(...)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:582
  crypto/tls.(*Conn).Read(0xc0003cd180, {0xc000a0e000, 0x1000, 0x0?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:1285 +0x16f
  bufio.(*Reader).Read(0xc00001cba0, {0xc000220900, 0x9, 0xc000aada08?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:236 +0x1b4
  io.ReadAtLeast({0x279e600, 0xc00001cba0}, {0xc000220900, 0x9, 0x9}, 0x9)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:331 +0x9a
  io.ReadFull(...)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:350
  golang.org/x/net/http2.readFrameHeader({0xc000220900?, 0x9?, 0xc000000000?}, {0x279e600?, 0xc00001cba0?})
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/frame.go:237 +0x6e
  golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002208c0)
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/frame.go:498 +0x95
  golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000096f98)
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:2225 +0x130
  golang.org/x/net/http2.(*ClientConn).readLoop(0xc0004d6000)
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:2120 +0x6f
  created by golang.org/x/net/http2.(*Transport).newClientConn
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:818 +0xc1c
  
  goroutine 3652 [select, 42 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00105c640)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3342 [select, 44 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0009d3400)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3838 [select, 41 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc001306a40)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3326 [select, 44 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0009d2e80)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3628 [chan receive, 42 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3457 [chan receive, 43 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3500 [select, 43 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00085e940)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3480 [select, 43 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00085e180)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3659 [select, 42 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00105d440)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 13698 [chan receive]:
  testing.(*T).Run(0xc00069aea0, {0x23f19a5?, 0x3b60c78?}, 0xc000b615f0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
  github.com/apache/camel-k/v2/e2e/commonwithcustominstall.TestKamelReset.func1({0xc000b21890, 0x29})
  	/home/runner/work/camel-k/camel-k/e2e/commonwithcustominstall/reset_test.go:39 +0x115
  github.com/apache/camel-k/v2/e2e/support.invokeUserTestCode(0xc00069aea0, {0xc000b21890, 0x29}, 0xc0008f1f50)
  	/home/runner/work/camel-k/camel-k/e2e/support/test_support.go:2472 +0xf1
  github.com/apache/camel-k/v2/e2e/support.WithNewTestNamespace(0xc00069aea0, 0x0?)
  	/home/runner/work/camel-k/camel-k/e2e/support/test_support.go:2411 +0xdb
  github.com/apache/camel-k/v2/e2e/commonwithcustominstall.TestKamelReset(0x1a32c01?)
  	/home/runner/work/camel-k/camel-k/e2e/commonwithcustominstall/reset_test.go:35 +0x35
  testing.tRunner(0xc00069aea0, 0x256a868)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f
  
  goroutine 3821 [select, 41 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc001306180)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3808 [chan receive, 41 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3320 [chan receive, 44 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3300 [syscall, 44 minutes]:
  os/signal.signal_recv()
  	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/sigqueue.go:151 +0x2f
  os/signal.loop()
  	/opt/hostedtoolcache/go/1.18.10/x64/src/os/signal/signal_unix.go:23 +0x19
  created by os/signal.Notify.func1.1
  	/opt/hostedtoolcache/go/1.18.10/x64/src/os/signal/signal.go:151 +0x2a
  
  goroutine 13820 [select]:
  github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc0000fcaf0, {0x27b1660?, 0xc0000fb900}, 0x1, {0x0, 0x0, 0x0})
  	/home/runner/go/pkg/mod/github.com/onsi/gomega@v1.27.6/internal/async_assertion.go:538 +0x8c9
  github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc0000fcaf0, {0x27b1660, 0xc0000fb900}, {0x0, 0x0, 0x0})
  	/home/runner/go/pkg/mod/github.com/onsi/gomega@v1.27.6/internal/async_assertion.go:145 +0x8d
  github.com/apache/camel-k/v2/e2e/commonwithcustominstall.TestKamelReset.func1.1(0xc0000837b0?)
  	/home/runner/work/camel-k/camel-k/e2e/commonwithcustominstall/reset_test.go:43 +0x208
  testing.tRunner(0xc0013a24e0, 0xc000b615f0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
  created by testing.(*T).Run
```

**Comment by squakez** [comment]
Also the promote tests are failing, likely for the same reason:
```
TestKamelCLIPromote (0s)
❌ TestKamelCLIPromote/binding_dev (0s)
  binding "kb-timer-source-to-log" created
  panic: test timed out after 1h0m0s
  
  goroutine 13289 [running]:
  testing.(*M).startAlarm.func1()
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:2029 +0x8e
  created by time.goFunc
  	/opt/hostedtoolcache/go/1.18.10/x64/src/time/sleep.go:176 +0x32
  
  goroutine 1 [chan receive, 4 minutes]:
  testing.(*T).Run(0xc0006c8b60, {0x23e9a8a?, 0x5222e5?}, 0x256d7c0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
  testing.runTests.func1(0xc00021ce40?)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1839 +0x6e
  testing.tRunner(0xc0006c8b60, 0xc00093fcd8)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
  testing.runTests(0xc00032b900?, {0x3afdb00, 0x12, 0x12}, {0x7f979a583108?, 0x40?, 0x3b31b20?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1837 +0x457
  testing.(*M).Run(0xc00032b900)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1719 +0x5d9
  main.main()
  	_testmain.go:81 +0x1aa
  
  goroutine 59 [IO wait]:
  internal/poll.runtime_pollWait(0x7f97707201d8, 0x72)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0x89
  internal/poll.(*pollDesc).wait(0xc000404e00?, 0xc000b68000?, 0x0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
  internal/poll.(*pollDesc).waitRead(...)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
  internal/poll.(*FD).Read(0xc000404e00, {0xc000b68000, 0xfe5b, 0xfe5b})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x25a
  net.(*netFD).Read(0xc000404e00, {0xc000b68000?, 0xc000828120?, 0xc000b68048?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x29
  net.(*conn).Read(0xc000824000, {0xc000b68000?, 0x3ddb?, 0xc000828120?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x45
  crypto/tls.(*atLeastReader).Read(0xc00115f920, {0xc000b68000?, 0x0?, 0x0?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:785 +0x3d
  bytes.(*Buffer).ReadFrom(0xc0003cd3f8, {0x27a2580, 0xc00115f920})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/buffer.go:204 +0x98
  crypto/tls.(*Conn).readFromUntil(0xc0003cd180, {0x27a7c40?, 0xc000824000}, 0xfe18?)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:807 +0xe5
  crypto/tls.(*Conn).readRecordOrCCS(0xc0003cd180, 0x0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:614 +0x116
  crypto/tls.(*Conn).readRecord(...)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:582
  crypto/tls.(*Conn).Read(0xc0003cd180, {0xc00086b000, 0x1000, 0x0?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/crypto/tls/conn.go:1285 +0x16f
  bufio.(*Reader).Read(0xc0003543c0, {0xc000220900, 0x9, 0xc000afe208?})
  	/opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:236 +0x1b4
  io.ReadAtLeast({0x27a2380, 0xc0003543c0}, {0xc000220900, 0x9, 0x9}, 0x9)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:331 +0x9a
  io.ReadFull(...)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:350
  golang.org/x/net/http2.readFrameHeader({0xc000220900?, 0x9?, 0xc000000000?}, {0x27a2380?, 0xc0003543c0?})
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/frame.go:237 +0x6e
  golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002208c0)
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/frame.go:498 +0x95
  golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0006aff98)
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:2225 +0x130
  golang.org/x/net/http2.(*ClientConn).readLoop(0xc000210780)
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:2120 +0x6f
  created by golang.org/x/net/http2.(*Transport).newClientConn
  	/home/runner/go/pkg/mod/golang.org/x/net@v0.9.0/http2/transport.go:818 +0xc1c
  
  goroutine 31 [chan receive, 60 minutes]:
  knative.dev/pkg/metrics.(*metricsWorker).start(0xc00011e700)
  	/home/runner/go/pkg/mod/knative.dev/pkg@v0.0.0-20221123011842-b78020c16606/metrics/metrics_worker.go:99 +0x2f
  created by knative.dev/pkg/metrics.init.0
  	/home/runner/go/pkg/mod/knative.dev/pkg@v0.0.0-20221123011842-b78020c16606/metrics/exporter.go:39 +0xae
  
  goroutine 30 [select]:
  go.opencensus.io/stats/view.(*worker).start(0xc000342680)
  	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0xad
  created by go.opencensus.io/stats/view.init.0
  	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d
  
  goroutine 12514 [chan receive]:
  testing.(*T).Run(0xc0013cc1a0, {0x23d8f50?, 0x23cfd18?}, 0xc000688f00)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
  github.com/apache/camel-k/v2/e2e/commonwithcustominstall.TestKamelCLIPromote.func1({0xc0009b82d0, 0x29})
  	/home/runner/work/camel-k/camel-k/e2e/commonwithcustominstall/promote_test.go:72 +0x33b
  github.com/apache/camel-k/v2/e2e/support.invokeUserTestCode(0xc0013cc1a0, {0xc0009b82d0, 0x29}, 0xc000b65f40)
  	/home/runner/work/camel-k/camel-k/e2e/support/test_support.go:2507 +0xf1
  github.com/apache/camel-k/v2/e2e/support.WithNewTestNamespace(0xc0013cc1a0, 0x5222e5?)
  	/home/runner/work/camel-k/camel-k/e2e/support/test_support.go:2446 +0xdb
  github.com/apache/camel-k/v2/e2e/commonwithcustominstall.TestKamelCLIPromote(0xc0013cc1a0)
  	/home/runner/work/camel-k/camel-k/e2e/commonwithcustominstall/promote_test.go:40 +0x8a
  testing.tRunner(0xc0013cc1a0, 0x256d7c0)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f
  
  goroutine 3509 [select, 43 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000f6e740)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3319 [chan receive, 44 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3353 [select, 44 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00068ba80)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 13241 [select]:
  github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc000414380, {0x27b5570?, 0xc000ea58e0}, 0x1, {0x0, 0x0, 0x0})
  	/home/runner/go/pkg/mod/github.com/onsi/gomega@v1.27.6/internal/async_assertion.go:538 +0x8c9
  github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc000414380, {0x27b5570, 0xc000ea58e0}, {0x0, 0x0, 0x0})
  	/home/runner/go/pkg/mod/github.com/onsi/gomega@v1.27.6/internal/async_assertion.go:145 +0x8d
  github.com/apache/camel-k/v2/e2e/commonwithcustominstall.TestKamelCLIPromote.func1.3(0x1?)
  	/home/runner/work/camel-k/camel-k/e2e/commonwithcustominstall/promote_test.go:75 +0x29e
  testing.tRunner(0xc0013cc000, 0xc000688f00)
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f
  
  goroutine 3324 [select, 44 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00068b2c0)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3335 [syscall, 44 minutes]:
  os/signal.signal_recv()
  	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/sigqueue.go:151 +0x2f
  os/signal.loop()
  	/opt/hostedtoolcache/go/1.18.10/x64/src/os/signal/signal_unix.go:23 +0x19
  created by os/signal.Notify.func1.1
  	/opt/hostedtoolcache/go/1.18.10/x64/src/os/signal/signal.go:151 +0x2a
  
  goroutine 3706 [select, 42 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc001116740)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3844 [select, 41 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc0007ded40)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3870 [select, 41 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000312f40)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3671 [select, 42 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000a2f800)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3489 [select, 43 minutes]:
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc000312ec0)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:116 +0x38f
  created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.25.6/pkg/watch/streamwatcher.go:76 +0x130
  
  goroutine 3504 [chan receive, 43 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3840 [chan receive, 41 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
  
  goroutine 3659 [chan receive, 42 minutes]:
  github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run.func1()
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:99 +0x6a
  created by github.com/apache/camel-k/v2/pkg/cmd.(*debugCmdOptions).run
  	/home/runner/work/camel-k/camel-k/pkg/cmd/debug.go:98 +0x3fb
❌ TestKamelCLIPromote/kamelet_integration_dev (0s)
  Integration "timer-kamelet-usage" created
❌ TestKamelCLIPromote/plain_integration_dev (0s)
  No IntegrationPlatform resource in test-03a4fe64-ab88-44d5-a80a-f80eb8a749d7 namespace
  Integration "promote-route" created
  ```
