### ISSUE TITLE
No such property: header for class: Script1

### ISSUE THREAD

**Issue by lsergio** [apache/camel-k#4385]
I'm trying to create a basic Integration with toD and dynamic properties, like this:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test
spec:
  sources:
  - name: main.groovy
    content: |-
      rest("/test")
        .get()
        .to("direct:start");

      from("direct:start")
        .toD("${header.foo}");
```
as described at https://camel.apache.org/components/3.20.x/eips/toD-eip.html

But the integration creation fails with:

```
2023-05-17 14:08:30,037 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): groovy.lang.MissingPropertyException: No such property: header for class: Script1
[1] 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
[1] 	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
[1] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
[1] 	at Script1.run(Script1.groovy:5)
```

I get a similar error with ${body[id]} and possibily other examples. 

Using Camel K 1.12.0

Should this work?

**Comment by lburgazzoli** [comment]
as this is groovy, if you are usong double quoted strings, they are interpreted as gstrings and interpolated by groovy.

in your case, you should use single quoted strings, like '${header.foo}'
