### ISSUE TITLE
E2E - Recurrent golang stacktrace logs 

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#4754]
### What happened?

While looking at some github action tests logs I noticed a few golang stacktraces that do not impact the completion/result of the tests but produce a lot of noise in the logs.

One of the only relevant reference I could find was this issue: https://github.com/solo-io/gloo/issues/8548. It could be a result of [zap upgrade](https://github.com/apache/camel-k/pull/4748).

### Steps to reproduce

Look into an github action raw logs ([common](https://github.com/apache/camel-k/actions/workflows/common.yml?query=branch%3Amain)) -- preferably on passing tests.

### Relevant log output

The trace is:
```shell

2023-09-15T13:52:02.6249978Z [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
2023-09-15T13:52:02.6250380Z goroutine 42 [running]:
2023-09-15T13:52:02.6250665Z runtime/debug.Stack()
2023-09-15T13:52:02.6251487Z 	/opt/hostedtoolcache/go/1.20.8/x64/src/runtime/debug/stack.go:24 +0x65
2023-09-15T13:52:02.6252078Z sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
2023-09-15T13:52:02.6252726Z 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/log.go:59 +0xbd
...
```

### Camel K version

main branch

**Comment by squakez** [comment]
I think I saw this in some code refactoring for https://github.com/apache/camel-k/pull/4693 as well. The codegen client was failing and I fixed it in https://github.com/apache/camel-k/pull/4693/commits/dea0159627af84b14d9ddd733b7198f0cb20fbff#diff-86796b17887d2911710b145814e1a09d041afe84f364546f71daf3d4c12972b9 - not sure if we need to adopt the same strategy though.

**Comment by gansheer** [comment]
I'll try to add this change to the test init then :+1:
