### ISSUE TITLE
Logger error in `--dev` mode

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#4770]
When running a `--dev` we have the following error:
```
$ ./kamel run test.yaml --dev
Integration "test" created
Progress: integration "test" in phase Initialization
Cannot reconcile Integration test: error during trait customization: mount trait execution failed: unable to find integration container: test
Progress: integration "test" in phase Building Kit
Condition "IntegrationPlatformAvailable" is "True" for Integration test: default/camel-k
Integration "test" in phase "Initialization"
Integration "test" in phase "Building Kit"
Condition "IntegrationKitAvailable" is "False" for Integration test: creating a new integration kit
Integration Kit "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Build Submitted"
Build "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Scheduling"
Build "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Pending"
Build "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Running"
Integration Kit "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Build Running"
Build "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Succeeded"
Integration Kit "kit-ck9uq0r8f9vc73c3pdu0", created by Integration "test", changed phase to "Ready"
Progress: integration "test" in phase Deploying
Condition "IntegrationKitAvailable" is "True" for Integration test: kit-ck9uq0r8f9vc73c3pdu0
Integration "test" in phase "Deploying"
Progress: integration "test" in phase Running
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/log.go:59 +0xcd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc0003531c0, {0x25b7381, 0x7})
	sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/deleg.go:147 +0x45
github.com/go-logr/logr.Logger.WithName(...)
	github.com/go-logr/logr@v1.2.4/logr.go:336
github.com/apache/camel-k/v2/pkg/util/log.Logger.WithName({{{0x29e9558?, 0xc0003531c0?}, 0x30?}}, {0x25b7381?, 0xc0000fe4b0?})
	github.com/apache/camel-k/v2/pkg/util/log/log.go:81 +0x45
github.com/apache/camel-k/v2/pkg/util/log.WithName(...)
	github.com/apache/camel-k/v2/pkg/util/log/log.go:186
github.com/apache/camel-k/v2/pkg/util/kubernetes/log.NewSelectorScraper({0x7f641d637ac0?, 0xc000614380}, {0xc000b89c00, 0x7}, {0xc000b89bf8, 0x4}, {0xc0000fe4b0, 0x21}, 0x0)
	github.com/apache/camel-k/v2/pkg/util/kubernetes/log/annotation_scraper.go:57 +0x85
github.com/apache/camel-k/v2/pkg/util/kubernetes/log.PrintUsingSelector({0x29e3dc8, 0xc00063fd10}, 0xc000a4d838?, {0x7f641d637ac0?, 0xc000614380?}, {0xc000b89c00?, 0x5?}, {0xc000b89bf8?, 0x7?}, {0xc0000fe4b0, ...}, ...)
```
We have observed this in the past due to the change of ctrl dependencies.

The integration run correctly, it's just a cosmetic issue.

**Comment by squakez** [comment]
@gansheer if you have some time to look at it.

**Comment by gansheer** [comment]
Sur, I'll look into it.
