### ISSUE TITLE
log.SetLogger(...) was never called

### ISSUE THREAD

**Issue by apupier** [apache/camel-k#4891]
### What happened?

During automated test execution , i noticed a stack in log:

```
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 45 [running]:
runtime/debug.Stack()
    runtime/debug/stack.go:24 +0x5e
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
    sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/log.go:59 +0xcd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc0000c0b80, {0x25d5c56, 0x7})
    sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/deleg.go:147 +0x45
github.com/go-logr/logr.Logger.WithName(...)
    github.com/go-logr/logr@v1.2.4/logr.go:336
github.com/apache/camel-k/v2/pkg/util/log.Logger.WithName({{{0x2a0a558?, 0xc0000c0b80?}, 0x0?}}, {0x25d5c56?, 0xc8?})
    github.com/apache/camel-k/v2/pkg/util/log/log.go:81 +0x45
github.com/apache/camel-k/v2/pkg/util/log.WithName(...)
    github.com/apache/camel-k/v2/pkg/util/log/log.go:186
github.com/apache/camel-k/v2/pkg/util/kubernetes/log.NewPodScraper({0x7fdca52e4100?, 0xc000145300}, {0xc0009ca3b0, 0x7}, {0xc00084de80, 0x20}, {0xc0009ca3a0, 0xf}, 0x0)
    github.com/apache/camel-k/v2/pkg/util/kubernetes/log/pod_scraper.go:62 +0x85
github.com/apache/camel-k/v2/pkg/util/kubernetes/log.(*SelectorScraper).addPodScraper(0xc0004050e0, {0x2a059b8, 0xc000533ef0}, {0xc00084de80, 0x20}, 0xc0005a1600)
    github.com/apache/camel-k/v2/pkg/util/kubernetes/log/annotation_scraper.go:135 +0x89
github.com/apache/camel-k/v2/pkg/util/kubernetes/log.(*SelectorScraper).synchronize(0xc0004050e0, {0x2a059b8, 0xc000533ef0}, 0xc0005a1600?)
    github.com/apache/camel-k/v2/pkg/util/kubernetes/log/annotation_scraper.go:108 +0x1c7
github.com/apache/camel-k/v2/pkg/util/kubernetes/log.(*SelectorScraper).periodicSynchronize(0xc0004050e0, {0x2a059b8?, 0xc000533ef0}, 0xc0005a1600, 0xc000011fc8)
    github.com/apache/camel-k/v2/pkg/util/kubernetes/log/annotation_scraper.go:77 +0x4c
created by github.com/apache/camel-k/v2/pkg/util/kubernetes/log.(*SelectorScraper).periodicSynchronize in goroutine 134
    github.com/apache/camel-k/v2/pkg/util/kubernetes/log/annotation_scraper.go:94 +0x190
 ```

### Steps to reproduce

do not know. My guess is that there is an attempt to access logs but the integration has just been deleted

### Camel K version

2.1.0

**Comment by squakez** [comment]
Seen in #4770 and #4754
