### ISSUE TITLE
OGNL Script not working anymore after upgrade to Camel-K 2.1.0

### ISSUE THREAD

**Issue by andy-d2019** [apache/camel-k#4936]
### What happened?

I used the following step in a Kamelet:

```
- set-body:
       ognl: request.body.query(getProperty('data'), @{{result-class}}@class)
```

It used to work in conjunction with camel-k 1.12.0, but after upgrading to camel-k 2.1.0 i get the following error:

```
java.lang.NullPointerException: target is null for method getProperty
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:72)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:171)
	at ognl.SimpleNode.getValue(SimpleNode.java:206)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:69)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:171)
	at ognl.SimpleNode.getValue(SimpleNode.java:206)
	at ognl.ASTChain.getValueBody(ASTChain.java:117)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:171)
	at ognl.SimpleNode.getValue(SimpleNode.java:206)
	at ognl.Ognl.getValue(Ognl.java:408)
	at ognl.Ognl.getValue(Ognl.java:383)
	at org.apache.camel.language.ognl.OgnlExpression.evaluate(OgnlExpression.java:56)
	at org.apache.camel.processor.SetBodyProcessor.process(SetBodyProcessor.java:45)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:475)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.executeReactiveWork(DefaultReactiveExecutor.java:196)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:164)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:163)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:383)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:208)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
```

The Kamelet in Question:

```
apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: influx-query-action
  annotations:
    camel.apache.org/kamelet.support.level: "Stable"
    camel.apache.org/catalog.version: "4.1.0-SNAPSHOT"
    camel.apache.org/kamelet.icon: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE2LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPg0KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgd2lkdGg9IjUxMnB4IiBoZWlnaHQ9IjUxMnB4IiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgNTEyIDUxMjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPGc+DQoJPHBhdGggZD0iTTQ0OCwwSDY0QzQ2LjMyOCwwLDMyLDE0LjMxMywzMiwzMnY0NDhjMCwxNy42ODgsMTQuMzI4LDMyLDMyLDMyaDM4NGMxNy42ODgsMCwzMi0xNC4zMTIsMzItMzJWMzINCgkJQzQ4MCwxNC4zMTMsNDY1LjY4OCwwLDQ0OCwweiBNNjQsNDgwVjEyOGg4MHY2NEg5NnYxNmg0OHY0OEg5NnYxNmg0OHY0OEg5NnYxNmg0OHY0OEg5NnYxNmg0OHY4MEg2NHogTTQ0OCw0ODBIMTYwdi04MGgyNTZ2LTE2DQoJCUgxNjB2LTQ4aDI1NnYtMTZIMTYwdi00OGgyNTZ2LTE2SDE2MHYtNDhoMjU2di0xNkgxNjB2LTY0aDI4OFY0ODB6Ii8+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8L3N2Zz4NCg=="
    camel.apache.org/provider: "Apache Software Foundation"
    camel.apache.org/kamelet.group: "company"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  dependencies:
  - "mvn:com.influxdb:influxdb-client-java:6.10.0"
  - "mvn:company:library:0.2.36-SNAPSHOT"
  dataTypes:
     out:
      default: json
      types:
        json:
          mediaType: application/json
  definition:
    title: "Influx-Query-Action"
    description: |-
     This action retrieves a collection of flux Results converted to a Pojo List.
    type: object
    required:
        - influx-url
        - influx-token
        - influx-organization
        - result-class
    properties:
        influx-url:
          title: Address to locate the influxdb
          example: http://localhost:8086
          type: string
        influx-token:
          title: The token used to access the influx db
          example: asdwqe23
          type: string
        influx-organization:
          title: The organization used by the influx query api.
          example: company
          type: string
        result-class:
          title: The type of the pojo list to be returned.
          example: company.event.Temperature
  template:
    from:
      uri: "kamelet:source"
      steps:
         - set-property:
            name: data
            ognl: request.body
         - set-body:
             ognl: "@com.influxdb.client.InfluxDBClientFactory@create('{{influx-url}}', '{{influx-token}}'.toCharArray(), '{{influx-organization}}')"
         - set-body:
             ognl: request.body.getQueryApi()
         - to: "log:info"
         - log: "${exchangeProperty.data}"
         - set-body:
               ognl: request.body.query(getProperty("data"), @{{result-class}}@class)
         - to: "log:info"
```

Other variants like property('data') and properties['data'] produce similar errors.

### Steps to reproduce

Using inline OGNL within a method call in an OGNL Script seems to trigger the issue.
It looks like OGNL is resolved differently in Camel-K 1.12 and 2.1.0.

### Relevant log output

```shell
Camel K was installed with OML 0.26.0 and the Operator from Operatorhub.io
```

### Camel K version

2.1.0

**Comment by squakez** [comment]
Please consider that upgrading to 2.10 version would set by default the Camel Runtime to version 4.0.0 (it was 3.20 in version 1.12). I think there could be a difference and you probably need to upgrade to the new accepted notation. Mind that you can keep [running older version of Camel via `-t camel.runtimve-version`](https://camel.apache.org/camel-k/2.1.x/running/runtime-version.html).

**Comment by andy-d2019** [comment]
The notation should be correct according to the documentation for Camel 4.0.0:
https://camel.apache.org/components/4.0.x/languages/ognl-language.html

If it is not i would greatly appreciate help with the notation.

**Comment by andy-d2019** [comment]
I circumvented the issue for now using a mix of ognl and simple, to call a method with a static .class and an exchange property.

```- set-property:
            name: classToSet
            ognl: "@{{result-class}}@class"
      - set-body:
             simple: "${body.query(${exchangeProperty.data},  ${exchangeProperty.classToSet})}"```

**Comment by squakez** [comment]
I've had a look and it seems the behavior of the `getProperty()` changed from Camel 3 to Camel 4 though I did not manage to find any reference in the migration guides. At this stage I'm not sure if this could be even a bug. Here a simpler reproducer:
```
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - setProperty:
          name: data
          simple: "2"
      - setBody:
             ognl: "@java.lang.String@valueOf('1')"
      - setBody:
            ognl: request.body.replaceAll('1', getProperty("data"))
      - log: "${body}"
  ```
Running it with Camel K or Camel JBang against Camel version 3.20.1 works. (`camel run --camel-version=3.20.1 test.yaml`) When however we run it against version 4.0.0 fails with following error:
```
2023-12-05 16:04:28.067  WARN 1135657 --- [ - timer://yaml] camel.component.timer.TimerConsumer : Error processing exchange. Exchange[544E3B0719CDF54-0000000000000001]. Caused by: [java.lang.NullPointerException - target is null for method getProperty]
java.lang.NullPointerException: target is null for method getProperty
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:72) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:171) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.SimpleNode.getValue(SimpleNode.java:206) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:69) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:171) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.SimpleNode.getValue(SimpleNode.java:206) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.ASTChain.getValueBody(ASTChain.java:117) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:171) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.SimpleNode.getValue(SimpleNode.java:206) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.Ognl.getValue(Ognl.java:408) ~[ognl-3.4.1.jar:3.4.1]
	at ognl.Ognl.getValue(Ognl.java:383) ~[ognl-3.4.1.jar:3.4.1]
	at org.apache.camel.language.ognl.OgnlExpression.evaluate(OgnlExpression.java:56) ~[camel-ognl-4.0.0.jar:4.0.0]
	at org.apache.camel.processor.SetBodyProcessor.process(SetBodyProcessor.java:45) ~[camel-core-processor-4.0.0.jar:4.0.0]
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:475) ~[camel-core-processor-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.executeReactiveWork(DefaultReactiveExecutor.java:196) [camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:164) [camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59) [camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:163) [camel-core-processor-4.0.0.jar:4.0.0]
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:383) [camel-base-engine-4.0.0.jar:4.0.0]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:208) [camel-timer-4.0.0.jar:4.0.0]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76) [camel-timer-4.0.0.jar:4.0.0]
	at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
	at java.util.TimerThread.run(Timer.java:516) [?:?]
```
@oscerd @davsclaus is this an expected change or is it possibly a bug? it seems that the `getProperty()` method tries to run against some (null) object instead of trying to get the data from the context.

**Comment by davsclaus** [comment]
Maybe you are welcome to create a JIRA (low priority though as its ognl)

**Comment by davsclaus** [comment]
Okay found a fix and will be in next camel releases

**Comment by squakez** [comment]
Great, thanks for fixing!!
