### ISSUE TITLE
Unable to start knative route

### ISSUE THREAD

**Issue by kameshsampath** [apache/camel-k#506]
When i define a route like:

```
	from("knative:endpoint/s3filelogger")
				.to("log:info?showAll=true&showHeaders=true&showProperties=true&showOut=true")
				.end();
```
the route fails to start with exception

```
[1] 2019-02-28 07:42:42.588 INFO  [main] DefaultCamelContext - Apache Camel 2.23.1 (CamelContext: camel-k) is shutdown in 0.153 seconds
[1] Exception in thread "main" java.nio.channels.UnresolvedAddressException
[1]     at sun.nio.ch.Net.checkAddress(Net.java:101)
[1]     at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:218)
[1]     at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
[1]     at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
[1]     at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
[1]     at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
[1]     at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
[1]     at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
[1]     at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
[1]     at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
[1]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[1]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
[1]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[1]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[1]     at java.lang.Thread.run(Thread.java:748)

```

log snippet before shutdown of route
```
[1] 2019-02-28 07:42:41.880 DEBUG [main] DefaultCamelContext - Starting consumer (order: 1000) on route: route1
[1] 2019-02-28 07:42:41.885 DEBUG [main] DefaultManagementAgent - Registered MBean with ObjectName: org.apache.camel:context=camel-k,type=consumers,name=NettyHttpConsumer(0x53b7ce6)
[1] 2019-02-28 07:42:41.886 DEBUG [main] NettyHttpConsumer - Starting consumer: Consumer[http://s3filelogger]
[1] 2019-02-28 07:42:41.886 DEBUG [main] NettyConsumer - Netty consumer binding to: s3filelogger:80
[1] 2019-02-28 07:42:41.886 DEBUG [main] HttpServerBootstrapFactory - BootstrapFactory on port 80 is starting
[1] 2019-02-28 07:42:42.176 DEBUG [main] SingleTCPNettyServerBootstrapFactory - Created ServerBootstrap ServerBootstrap(ServerBootstrapConfig(group: NioEventLoopGroup, channelFactory: NioServerSocketChannel.class, options: {SO_REUSEADDR=true}, childGroup: NioEventLoopGroup, childOptions: {SO_KEEPALIVE=true, TCP_NODELAY=true, SO_REUSEADDR=true, CONNECT_TIMEOUT_MILLIS=10000}, childHandler: org.apache.camel.component.netty4.http.HttpServerInitializerFactory@4601203a))
[1] 2019-02-28 07:42:42.176 INFO  [main] SingleTCPNettyServerBootstrapFactory - ServerBootstrap binding to s3filelogger:80
[1] 2019-02-28 07:42:42.406 DEBUG [main] HttpServerBootstrapFactory - BootstrapFactory on port 80 is stopping
[1] 2019-02-28 07:42:42.407 INFO  [main] SingleTCPNettyServerBootstrapFactory - ServerBootstrap unbinding from s3filelogger:80
[1] 2019-02-28 07:42:42.422 DEBUG [main] HttpServerBootstrapFactory - BootstrapFactory on port 80 is removing consumer with context-path
[1] 2019-02-28 07:42:42.430 DEBUG [main] NettyConsumer - Netty consumer unbinding from: s3filelogger:80
[1] 2019-02-28 07:42:42.430 INFO  [main] NettyConsumer - Netty consumer unbound from: s3filelogger:80
[1] 2019-02-28 07:42:42.430 DEBUG [main] NettyHttpConsumer - Stopping consumer: Consumer[http://s3filelogger]
[1] 2019-02-28 07:42:42.433 DEBUG [main] LogProducer - Stopping producer: Producer[log://info?showAll=true&showHeaders=true&showOut=true&showProperties=true]
```

**Comment by kameshsampath** [comment]
adding integration and ksvc files 

https://gist.github.com/kameshsampath/c01ede757b55fe8d004f5b4c5926349e
