### ISSUE TITLE
Native build failed directly

### ISSUE THREAD

**Issue by pai911** [apache/camel-k#5080]
### What happened?

When deploying a simple route in Java DSL, I kept seeing runtime errors

```
╰─ klogs sample-674657f6d7-lzqtw
java.lang.InternalError: java.lang.reflect.InvocationTargetException
    at com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
    at com.oracle.svm.core.containers.Container.metrics(Container.java:44)
    at com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
    at com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:126)
    at com.oracle.svm.core.heap.PhysicalMemory.size(PhysicalMemory.java:92)
    at com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:362)
    at com.oracle.svm.core.JavaMainWrapper$EnterCreateIsolateWithCArgumentsPrologue.enter(JavaMainWrapper.java:387)
```

### Java Route
```
import org.apache.camel.builder.RouteBuilder;

public class Sample extends RouteBuilder {
  @Override
  public void configure() throws Exception {
          from("timer:tick")
        .log("Hello Camel K!");
  }
}
```

#### Step 1
```
╰─ kamel run -t quarkus.build-mode=native --trait container.request-memory=6Gi --trait container.limit-memory=6Gi Sample.java
Integration "sample" created
```
#### Step 2
```
╰─ kc get pod
NAME                               READY   STATUS             RESTARTS     AGE
camel-k-operator-cb5498fc6-gqxz8   1/1     Running            0            5d16h
sample-674657f6d7-lzqtw            0/1     CrashLoopBackOff   1 (4s ago)   5s
```
#### Step 3
```
╰─ klogs sample-674657f6d7-lzqtw
java.lang.InternalError: java.lang.reflect.InvocationTargetException
    at com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
    at com.oracle.svm.core.containers.Container.metrics(Container.java:44)
    at com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
    at com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:126)
    at com.oracle.svm.core.heap.PhysicalMemory.size(PhysicalMemory.java:92)
    at com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:362)
    at com.oracle.svm.core.JavaMainWrapper$EnterCreateIsolateWithCArgumentsPrologue.enter(JavaMainWrapper.java:387)
```

### Relevant log output

```shell
{"level":"info","ts":"2024-01-18T01:50:56Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"","phase-to":"Initialization"}
{"level":"info","ts":"2024-01-18T01:50:56Z","logger":"camel-k.controller.integration","msg":"Initializing Integration","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample"}
{"level":"info","ts":"2024-01-18T01:50:56Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Initialization","phase-to":"Building Kit"}
{"level":"info","ts":"2024-01-18T01:50:56Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Building Kit","phase-to":"Deploying"}
{"level":"info","ts":"2024-01-18T01:50:56Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Deploying","phase-to":"Running"}
{"level":"info","ts":"2024-01-18T01:51:04Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Running","phase-to":"Error"}
{"level":"info","ts":"2024-01-18T01:51:04Z","logger":"camel-k.controller.integration","msg":"Integration error","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","reason":"Error","error-message":"back-off 10s restarting failed container=integration pod=sample-674657f6d7-95kj4_camel(0a45e8ba-ed8a-454c-9867-b0d373e74ad5)"}
{"level":"info","ts":"2024-01-18T01:52:16Z","logger":"camel-k.cmd","msg":"v1apha1.KameletBinding is deprecated, please, use v1.Pipe instead\n"}
```

### Camel K version

Camel K Client 2.1.0  Camel K Operator 2.1.0

**Comment by squakez** [comment]
It seems to be an issue in GraalVM: https://github.com/oracle/graal/issues/7182 - Are you using default Integration base image or are you overriding? You can try to remove at all the trait as you probably won't need that much in a Quarkus native image in either way.

**Comment by pai911** [comment]
hi @squakez no I didn't override the base image.

and I got the same result even with the following command
```
kamel run -t quarkus.build-mode=native Sample.java
```

**Comment by pai911** [comment]
hi @squakez !

thank you for the ideas.

I tried to reset it, and tried to run it again

```
╰─ kc get pod
NAME                                       READY   STATUS      RESTARTS      AGE
camel-k-kit-cmkm65eue1pcq29mcr9g-builder   0/1     Completed   0             4m38s
camel-k-operator-cb5498fc6-gqxz8           1/1     Running     0             6d8h
sample-76d85b7d7c-dqsqh                    0/1     Error       1 (13s ago)   20s
```

The builder looks fine?
```
╰─ klogs camel-k-kit-cmkm65eue1pcq29mcr9g-builder
Defaulted container "spectrum" out of: spectrum, builder (init), quarkus-native (init), package (init)
{"level":"info","ts":"2024-01-18T17:46:45Z","logger":"camel-k.builder","msg":"Go Version: go1.21.0"}
{"level":"info","ts":"2024-01-18T17:46:45Z","logger":"camel-k.builder","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":"2024-01-18T17:46:45Z","logger":"camel-k.builder","msg":"Camel K Version: 2.1.0"}
{"level":"info","ts":"2024-01-18T17:46:45Z","logger":"camel-k","msg":"Running spectrum task in context directory: /builder/kit-cmkm65eue1pcq29mcr9g/context"}
{"level":"info","ts":"2024-01-18T17:46:45Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:45 Pulling base image eclipse-temurin:17 (insecure=false)..."}
{"level":"info","ts":"2024-01-18T17:46:46Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:46 Composing layers..."}
{"level":"info","ts":"2024-01-18T17:46:48Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:48 Pushing image docker-registry.netbase.com/camel/camel-k-kit-cmkm65eue1pcq29mcr9g:4795341470 (insecure=false)..."}
{"level":"info","ts":"2024-01-18T17:46:49Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:49 pushed blob: sha256:98812cccdac481871ec89ab18857f93e3418c678a40f73df23f037c41c5a7ff5"}
{"level":"info","ts":"2024-01-18T17:46:49Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:49 pushed blob: sha256:881ab84beb42b6199af4cf21f398ff51eb0089833249327da5bd8baa5413491e"}
{"level":"info","ts":"2024-01-18T17:46:49Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:49 pushed blob: sha256:d6bf5e40eff7a834012f418c69173d3ae5deb167f5d1c37b2adb6f05241dbd1a"}
{"level":"info","ts":"2024-01-18T17:46:51Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:51 pushed blob: sha256:182a4e8ff3be9492478f81d5ad44ec40ac0cf9d8079f38cb4c2e26f0d54e4690"}
{"level":"info","ts":"2024-01-18T17:46:51Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:51 pushed blob: sha256:c506251a0ae0b836353578bafa8d6aeb266158d3291ba4abbc2f5f8ccda6f742"}
{"level":"info","ts":"2024-01-18T17:46:52Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:52 pushed blob: sha256:df2fac849a4581b035132d99e203fd83dc65590ea565435a266cb0e14a508838"}
{"level":"info","ts":"2024-01-18T17:46:59Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:59 pushed blob: sha256:49696fc5bee670a621132170cc87abff7ebafa30c790104b09e33495464fb3ca"}
{"level":"info","ts":"2024-01-18T17:46:59Z","logger":"camel-k","msg":"spectrum - 2024/01/18 17:46:59 docker-registry.netbase.com/camel/camel-k-kit-cmkm65eue1pcq29mcr9g:4795341470: digest: sha256:54fc53ea2d82f7d86734cc68a2ff350b611600df4ec083b53b1f08dc18d7ef5f size: 1245"}
```

but the integration pod still failed with the same exception

```
╰─ klogs sample-76d85b7d7c-dqsqh
java.lang.InternalError: java.lang.reflect.InvocationTargetException
    at com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
    at com.oracle.svm.core.containers.Container.metrics(Container.java:44)
    at com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
    at com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:126)
    at com.oracle.svm.core.heap.PhysicalMemory.size(PhysicalMemory.java:92)
    at com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:362)
    at com.oracle.svm.core.JavaMainWrapper$EnterCreateIsolateWithCArgumentsPrologue.enter(JavaMainWrapper.java:387)
```

Operator's log
```
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k.controller.integrationplatform","msg":"Invoking action initialize","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k.controller.integrationplatform","msg":"Initializing IntegrationPlatform","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k","msg":"RuntimeVersion set to 3.2.0"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k","msg":"BaseImage set to eclipse-temurin:17"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k","msg":"LocalRepository set to /etc/maven/m2"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k","msg":"Timeout set to {5m0s}"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k","msg":"Maven Timeout set to 5m0s"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k.controller.integrationplatform","msg":"State transition","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k","phase-from":"","phase-to":"Creating"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k.controller.integrationplatform","msg":"Invoking action create","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k.controller.integrationplatform","msg":"Installing camel catalog: /camel-catalog-3.2.0.yaml","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:19Z","logger":"camel-k.controller.integrationplatform","msg":"Copying platform annotations to catalog: camel-catalog-3.2.0","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:20Z","logger":"camel-k.controller.integrationplatform","msg":"State transition","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k","phase-from":"Creating","phase-to":"Ready"}
{"level":"info","ts":"2024-01-18T17:42:20Z","logger":"camel-k.controller.integrationplatform","msg":"Invoking action monitor","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:24Z","logger":"camel-k.controller.integrationplatform","msg":"Invoking action monitor","request-namespace":"camel","request-name":"camel-k","api-version":"camel.apache.org/v1","kind":"IntegrationPlatform","ns":"camel","name":"camel-k"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"","phase-to":"Initialization"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integration","msg":"Initializing Integration","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Initialization","phase-to":"Building Kit"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action initialize","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"Initializing IntegrationKit","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"Initialization","phase-to":"Build Submitted"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.traits","msg":"This is a Quarkus native build: setting build configuration with build Pod strategy, and native container with 1 CPU core and 4 GiB memory. Make sure your cluster can handle it.","trait":"builder"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.traits","msg":"User defined build strategy pod","trait":"builder"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.traits","msg":"User defined build order strategy sequential","trait":"builder"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.build","msg":"Initializing Build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.build","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"","phase-to":"Scheduling"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.build","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"Scheduling","phase-to":"Pending"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.build","msg":"Build queue duration 910.829424ms","request-namespace":"camel","request-name":"sample","build-queue-duration":0.910829424,"api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:45Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:46Z","logger":"camel-k.controller.build","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"Pending","phase-to":"Running"}
{"level":"info","ts":"2024-01-18T17:42:46Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:46Z","logger":"camel-k.controller.integrationkit","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"Build Submitted","phase-to":"Build Running"}
{"level":"info","ts":"2024-01-18T17:42:46Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:42:46Z","logger":"camel-k.controller.integrationkit","msg":"Build running","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.build","msg":"Build duration 4m14s","request-namespace":"camel","request-name":"sample","build-attempt":0,"build-result":"Succeeded","build-duration":254,"api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.build","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"Build","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"Running","phase-to":"Succeeded"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action build","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k","msg":"Kit kit-cmkm65eue1pcq29mcr9g ready, notify integration: sample"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.integrationkit","msg":"State transition","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g","phase-from":"Build Running","phase-to":"Ready"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.integrationkit","msg":"Invoking action monitor","request-namespace":"camel","request-name":"kit-cmkm65eue1pcq29mcr9g","api-version":"camel.apache.org/v1","kind":"IntegrationKit","ns":"camel","name":"kit-cmkm65eue1pcq29mcr9g"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Building Kit","phase-to":"Deploying"}
{"level":"info","ts":"2024-01-18T17:47:03Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Deploying","phase-to":"Running"}
{"level":"info","ts":"2024-01-18T17:47:10Z","logger":"camel-k.controller.integration","msg":"First readiness after 4m25s","request-namespace":"camel","request-name":"sample","ready-after":265,"api-version":"","kind":"","ns":"camel","name":"sample"}
{"level":"info","ts":"2024-01-18T17:47:14Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","phase-from":"Running","phase-to":"Error"}
{"level":"info","ts":"2024-01-18T17:47:14Z","logger":"camel-k.controller.integration","msg":"Integration error","request-namespace":"camel","request-name":"sample","api-version":"camel.apache.org/v1","kind":"Integration","ns":"camel","name":"sample","reason":"Error","error-message":""}
{"level":"info","ts":"2024-01-18T17:47:23Z","logger":"camel-k.cmd","msg":"v1apha1.KameletBinding is deprecated, please, use v1.Pipe instead\n"}
```

Any idea on what I should try next? thank you!

**Comment by squakez** [comment]
That's really strange. Do a jvm build run correctly? Could you try to build any java Quarkus native application and try to deploy to the cluster manually? I have the feeling there is some incompatibilities between the hardware your cluster is running and the Quarkus logic. Also, just for the sake of testing, you can try to run the same experiment with Camel K version 2.2 that was released last week, although I think it's not going to change things as it seems a Quarkus runtime problem.

**Comment by squakez** [comment]
Waiting for some feedback before closing this.

**Comment by squakez** [comment]
Closing as waiting for feebdack. Please, reopen if still facing any issue.
