### ISSUE TITLE
Kamelet data type test failling with updated 4.4.1 kamelet

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#5553]
### What happened?

The yak test [kamelet-data-types.feature ](https://github.com/apache/camel-k/blob/main/e2e/yaks/common/kamelet-data-types/kamelet-data-types.feature) fails when I update the [data-type-action.kamelet.yaml](https://github.com/apache/camel-k/blob/release-2.3.x/e2e/yaks/common/kamelet-data-types/data-type-action.kamelet.yaml) file.
The other test [timer-to-log.yaml](https://github.com/apache/camel-k/blob/release-2.3.x/e2e/yaks/common/kamelet-data-types/timer-to-log.yaml) also fails with the same result.

The main changes on the data-types are from these PRs:
* https://github.com/apache/camel-kamelets/pull/1607
* https://github.com/apache/camel-kamelets/pull/1732

Is this a real case of failling test (which would mean some bug somewhere) or should they be rewritten completly to fit the updated way of how the data types should be added with Camel 4.4.1 ?

### Relevant log output

```shell
[1] 2024-05-20 08:02:02,068 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (Camel (camel-1) thread #1 - timer://tick) Failed delivery for (MessageId: 3B008C0D17120C0-00000000000001DE on ExchangeId: 3B008C0D17120C0-00000000000001DE). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Missing data type transformer from camel:any to type camel:binary on the exchange: Exchange[]
[1] 
[1] Message History (complete message history is disabled)
[1] ---------------------------------------------------------------------------------------------------------------------------------------
[1] Source                                   ID                             Processor                                          Elapsed (ms)
[1] event-source.kamelet.yaml:25             source/source                  from[timer://tick]                                            0
[1] 
[1] Stacktrace
[1] ---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.CamelExecutionException: Missing data type transformer from camel:any to type camel:binary on the exchange: Exchange[]
[1]     at org.apache.camel.processor.transformer.DataTypeProcessor.process(DataTypeProcessor.java:86)
[1]     at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
[1]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

### Camel K version

main, 2.3.x

**Comment by gansheer** [comment]
@lburgazzoli @oscerd
