### ISSUE TITLE
Restful sample does not work

### ISSUE THREAD

**Issue by pcnfernando** [apache/camel-k#589]
I'm trying to deploy below restful sample.

```js
// ****************
//
// Setup
//
// ****************

l = components.get('log')
l.exchangeFormatter = function(e) {
    return "log - body=" + e.in.body + ", headers=" + e.in.headers
}

c = restConfiguration()
c.component = 'undertow'
c.port = 8080

// ****************
//
// Functions
//
// ****************

function proc(e) {
    e.getIn().setHeader('RandomValue', Math.floor((Math.random() * 100) + 1))
}

// ****************
//
// Route
//
// ****************

rest()
    .path('/say/hello')
    .produces("text/plain")
    .get().route()
        .transform().constant("Hello World");

from('timer:js?period=1s')
    .routeId('js')
    .setBody()
        .constant('Hello Camel K')
    .process(proc)
    .to('log:info')` 
```

And running it by executing the below command.
`kamel run --name=withrest --dependency=camel-undertow examples/routes-rest.js`

The sample is not getting started.
![image](https://user-images.githubusercontent.com/15815199/55620665-0f5f9780-57b9-11e9-8705-b1c9a20c79fc.png)

Below are my current pods in the minishift cluster.
![image](https://user-images.githubusercontent.com/15815199/55620703-21d9d100-57b9-11e9-8837-133d51a0a88c.png)

When I try to get the logs, it hangs without returning.

**Comment by lburgazzoli** [comment]
can you attache the logs of the camel-k-operator ?

**Comment by pcnfernando** [comment]
[operator.log](https://github.com/apache/camel-k/files/3047691/operator.log)

**Comment by lburgazzoli** [comment]
The operator reports:

    "error":"cannot delete build config: no matches for kind \"BuildConfig\" in version \"build.openshift.io/v1\""

Looks like your minishift instance is having issues, I would recommend recreate it.

**Comment by tadayosi** [comment]
Not sure if it's the same issue but now with 1.0.0-M1-SNAPSHOT I got the following error when trying `kamel run --name=withrest --dependency=camel-rest --dependency=camel-undertow examples/routes-rest.js`:
```
[8] Exception in thread "main" ReferenceError: components is not defined
[8] 	at <js> :program(Unnamed:28:1022-1031)
[8] 	at org.graalvm.polyglot.Context.eval(Context.java:367)
[8] 	at org.apache.camel.k.loader.js.JavaScriptRoutesLoader$1.configure(JavaScriptRoutesLoader.java:58)
[8] 	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:442)
[8] 	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:409)
[8] 	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:390)
[8] 	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$addRoutes$0(AbstractCamelContext.java:1077)
[8] 	at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2404)
[8] 	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1077)
[8] 	at org.apache.camel.main.MainSupport.postProcessCamelContext(MainSupport.java:779)
[8] 	at org.apache.camel.main.MainSupport.initCamelContext(MainSupport.java:646)
[8] 	at org.apache.camel.main.Main.doInit(Main.java:108)
[8] 	at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:61)
[8] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:88)
[8] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:196)
[8] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[8] 	at org.apache.camel.k.main.Application.main(Application.java:44)
```

It looks like `components` is not available in a js route.
```
l = components.get('log')
```
Also tried `context.getComponent('log')` but the result is the same.

**Comment by tadayosi** [comment]
OK, rewriting the `components.get` part as follows fixes the error:
```
l = getContext().getComponent('log', true, false)
```
I'll fix other parts of the example and submit a pull req.

**Comment by tadayosi** [comment]
Hmm, now it looks like this part is broken. Not sure how to fix it.
```
function proc(e) {
    e.getIn().setHeader('RandomValue', Math.floor((Math.random() * 100) + 1))
}
[...]
    .process(proc)
```
Errors:
```
[1] 2019-07-25 02:24:18.327 WARN  [Camel (camel-k) thread #2 - timer://js] TimerConsumer - Error processing exchange. Exchange[ID-routes-5ccdc6b89-8dkqw-1564021436341-0-45]. Caused by: [java.lang.ClassCastException - java.lang.Object cannot be cast to com.oracle.truffle.polyglot.PolyglotLanguageContext]
[1] java.lang.ClassCastException: java.lang.Object cannot be cast to com.oracle.truffle.polyglot.PolyglotLanguageContext
[1] 	at com.oracle.truffle.polyglot.PolyglotLanguage$ContextProfile.profile(PolyglotLanguage.java:383) ~[org.graalvm.truffle.truffle-api-19.0.2.jar:?]
[1] 	at com.oracle.truffle.polyglot.HostToGuestRootNode.profileContext(HostToGuestRootNode.java:113) ~[org.graalvm.truffle.truffle-api-19.0.2.jar:?]
[1] 	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:72) ~[org.graalvm.truffle.truffle-api-19.0.2.jar:?]
[1] 	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102) ~[org.graalvm.truffle.truffle-api-19.0.2.jar:?]
[1] 	at com.oracle.truffle.polyglot.FunctionProxyHandler.invoke(HostInteropReflect.java:454) ~[org.graalvm.truffle.truffle-api-19.0.2.jar:?]
[1] 	at com.sun.proxy.$Proxy28.process(Unknown Source) ~[?:?]
[1] 	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryState.run(RedeliveryErrorHandler.java:480) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:185) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:87) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:222) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:193) [org.apache.camel.camel-timer-3.0.0-M4.jar:3.0.0-M4]
[1] 	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:75) [org.apache.camel.camel-timer-3.0.0-M4.jar:3.0.0-M4]
[1] 	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_191]
[1] 	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_191]
[1] Caused by: com.oracle.truffle.api.TruffleStackTrace$LazyStackTrace
```
