### ISSUE TITLE
Flaky Docker build process

### ISSUE THREAD

**Issue by gansheer** [apache/camel-k#5920]
### What happened?

The Nightly OLM test github action workflow sometime fails due to some timeout in mvnw internal downloads.

### Relevant log output

```shell
#12 [base  7/12] RUN tar -xC /usr/share/maven/mvnw/ -f /usr/share/maven/mvnw/mvnw.tar     && rm -v /usr/share/maven/mvnw/mvnw.tar     && sed -i "s;distributionUrl=.*;distributionUrl=https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip;" /usr/share/maven/mvnw/.mvn/wrapper/maven-wrapper.properties
#12 0.154 removed '/usr/share/maven/mvnw/mvnw.tar'
#12 DONE 0.2s

#13 [base  8/12] RUN /usr/share/maven/mvnw//mvnw --version | grep "Maven home:" | sed 's/Maven home: //' >> /usr/share/maven/mvnw/default     && cp -r /usr/share/maven/lib/. $(cat /usr/share/maven/mvnw/default)/lib     && rm $(cat /usr/share/maven/mvnw/default)/lib/maven-slf4j-provider*     && rm $(cat /usr/share/maven/mvnw/default)/lib/slf4j-api-1.*
#13 135.6 Exception in thread "main" java.net.ConnectException: Connection timed out
#13 135.6 	at java.base/sun.nio.ch.Net.connect0(Native Method)
#13 135.6 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
#13 135.6 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
#13 135.6 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
#13 135.6 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
#13 135.6 	at java.base/java.net.Socket.connect(Socket.java:633)
#13 135.6 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
#13 135.6 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
#13 135.6 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
#13 135.6 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
#13 135.6 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
#13 135.6 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
#13 135.6 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
#13 135.6 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
#13 135.6 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1256)
#13 135.6 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1142)
#13 135.6 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
#13 135.6 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1701)
#13 135.6 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
#13 135.6 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
#13 135.6 	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:109)
#13 135.6 	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:97)
#13 135.6 	at org.apache.maven.wrapper.Installer.createDist(Installer.java:94)
#13 135.6 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:151)
#13 135.6 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
#13 135.6 rm: cannot remove '/lib/maven-slf4j-provider*': No such file or directory
#13 ERROR: process "/bin/sh -c ${MVNW_DIR}/mvnw --version | grep \"Maven home:\" | sed 's/Maven home: //' >> ${MVNW_DIR}default     && cp -r /usr/share/maven/lib/. $(cat ${MVNW_DIR}default)/lib     && rm $(cat ${MVNW_DIR}default)/lib/maven-slf4j-provider*     && rm $(cat ${MVNW_DIR}default)/lib/slf4j-api-1.*" did not complete successfully: exit code: 1
------
 > [base  8/12] RUN /usr/share/maven/mvnw//mvnw --version | grep "Maven home:" | sed 's/Maven home: //' >> /usr/share/maven/mvnw/default     && cp -r /usr/share/maven/lib/. $(cat /usr/share/maven/mvnw/default)/lib     && rm $(cat /usr/share/maven/mvnw/default)/lib/maven-slf4j-provider*     && rm $(cat /usr/share/maven/mvnw/default)/lib/slf4j-api-1.*:
135.6 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
135.6 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1701)
135.6 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
135.6 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
135.6 	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:109)
135.6 	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:97)
135.6 	at org.apache.maven.wrapper.Installer.createDist(Installer.java:94)
135.6 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:151)
135.6 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
135.6 rm: cannot remove '/lib/maven-slf4j-provider*': No such file or directory
------
Dockerfile:43
--------------------
  42 |     # Install a default mvnw distribution at build time and prepare the config for formatting log
  43 | >>> RUN ${MVNW_DIR}/mvnw --version | grep "Maven home:" | sed 's/Maven home: //' >> ${MVNW_DIR}default \
  44 | >>>     && cp -r /usr/share/maven/lib/. $(cat ${MVNW_DIR}default)/lib \
  45 | >>>     && rm $(cat ${MVNW_DIR}default)/lib/maven-slf4j-provider* \
  46 | >>>     && rm $(cat ${MVNW_DIR}default)/lib/slf4j-api-1.*
  47 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c ${MVNW_DIR}/mvnw --version | grep \"Maven home:\" | sed 's/Maven home: //' >> ${MVNW_DIR}default     && cp -r /usr/share/maven/lib/. $(cat ${MVNW_DIR}default)/lib     && rm $(cat ${MVNW_DIR}default)/lib/maven-slf4j-provider*     && rm $(cat ${MVNW_DIR}default)/lib/slf4j-api-1.*" did not complete successfully: exit code: 1
make: *** [Makefile:441: image-build] Error 1
```

**Comment by squakez** [comment]
This is generic, it does not happen exclusively on that test. I guess it's some temporary networking issue when mvnw tries to download its internal structure.

**Comment by squakez** [comment]
I haven't noticed this problem in the last month. Let's close it for now. We can reopen if the problem appears again.
