### ISSUE TITLE
Camel-k-cache not able to create PVC (pod has unbound immediate PersistentVolumeClaims)

### ISSUE THREAD

**Issue by asifdxtreme** [apache/camel-k#898]
I am running camel-k on K8s(v1.15.1), camel-k-operator comes up fine but the `came-k-cache` always remains in the `Pending` phase, as per the logs of camel-k-cache pod the PVC Claim fails and it's not able to schedule. Below are the logs from the env.

```
~$ kubectl get pods
NAME                               READY   STATUS    RESTARTS   AGE
camel-k-cache                      0/1     Pending   0          11h
camel-k-operator-85699785f-22t9m   1/1     Running   0          11h

```
```
~$ kubectl describe pod camel-k-cache
Name:         camel-k-cache
Namespace:    default
Priority:     0
Node:         <none>
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:           
Init Containers:
  create-kaniko-cache:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      mkdir
      -p
      /workspace/cache
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xldvs (ro)
      /workspace from camel-k-builder (rw)
Containers:
  warm-kaniko-cache:
    Image:      gcr.io/kaniko-project/warmer:v0.9.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --cache-dir=/workspace/cache
      --image=fabric8/s2i-java:3.0-java8
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xldvs (ro)
      /workspace from camel-k-builder (rw)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  camel-k-builder:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  camel-k
    ReadOnly:   false
  default-token-xldvs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xldvs
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m32s (x480 over 11h)  default-scheduler  pod has unbound immediate PersistentVolumeClaims

```
```
~$ kubectl describe pvc camel-k
Name:          camel-k
Namespace:     default
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=camel-k
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    camel-k-cache
Events:
  Type    Reason         Age                    From                         Message
  ----    ------         ----                   ----                         -------
  Normal  FailedBinding  3m1s (x2863 over 11h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

```

**Comment by jamesnetherton** [comment]
Sounds like the same issue as https://github.com/apache/camel-k/issues/736.

**Comment by asifdxtreme** [comment]
After manually creating a StorageClass and PV the `camel-k-cache` pod comes into Error State, below is the logs from the pod
```
~$ kubectl logs camel-k-cache
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf13712]

goroutine 1 [running]:
github.com/GoogleContainerTools/kaniko/pkg/cache.WarmCache(0x1977fe0, 0xf25480, 0xc420371cd8)
	/go/src/github.com/GoogleContainerTools/kaniko/pkg/cache/warm.go:47 +0x372
github.com/GoogleContainerTools/kaniko/cmd/warmer/cmd.glob..func2(0x196f140, 0xc4203fa200, 0x0, 0x2)
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/warmer/cmd/root.go:54 +0x2d
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).execute(0x196f140, 0xc4200b2070, 0x2, 0x2, 0x196f140, 0xc4200b2070)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x196f140, 0x0, 0x4, 0x116cca9)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra.(*Command).Execute(0x196f140, 0xc420371f78, 0xc4200ac058)
	/go/src/github.com/GoogleContainerTools/kaniko/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/GoogleContainerTools/kaniko/cmd/warmer/main.go:26 +0x2d
```
