### ISSUE TITLE
routes.yaml example fails with NoSuchLanguageException

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-k#929]
The body uppercase transformation in the [routes.yaml](https://github.com/apache/camel-k/blob/master/examples/routes.yaml#L10) example results in:

```
2019-09-10 08:50:02.245 WARN  [Camel (camel-k) thread #2 - timer://tick] TimerConsumer - Error processing exchange. Exchange[ID-routes-6559d6b457-vlsxl-1568105397257-0-3]. Caused by: [org.apache.camel.NoSuchLanguageException - No language could be found for: bean]
org.apache.camel.NoSuchLanguageException: No language could be found for: bean
	at org.apache.camel.impl.engine.DefaultLanguageResolver.noSpecificLanguageFound(DefaultLanguageResolver.java:91) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.DefaultLanguageResolver.resolveLanguage(DefaultLanguageResolver.java:67) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.AbstractCamelContext.resolveLanguage(AbstractCamelContext.java:1619) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.support.builder.ExpressionBuilder$68.evaluate(ExpressionBuilder.java:1527) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:34) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.language.simple.SimpleExpressionBuilder$29.evaluate(SimpleExpressionBuilder.java:668) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:34) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.builder.SimpleBuilder.evaluate(SimpleBuilder.java:99) ~[org.apache.camel.camel-core-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.SetBodyProcessor.process(SetBodyProcessor.java:43) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryState.run(RedeliveryErrorHandler.java:480) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:185) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:87) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:222) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:193) [org.apache.camel.camel-timer-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:75) [org.apache.camel.camel-timer-3.0.0-M4.jar:3.0.0-M4]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_191]

```

If you manually add a dependency for `camel-bean` it works fine. Not sure if that's the intended way to make the example work, but it'd be nice if it worked OOTB.

**Comment by lburgazzoli** [comment]
it maybe because of some relocation of classes in camel 3 rc1, we probably need to add camel-bean as common dependency
